"""
Interactive Diagram Viewer with Visual Canvas Editor
Includes all tabs: Mermaid Code, HTML Visualization, Interactive Editor (with paste-to-canvas), Export
"""

import streamlit as st
import json
import zlib
import base64
from pathlib import Path


def render_diagram_viewer(diagram_file: Path, meeting_notes: str = ""):
    """
    Render interactive diagram viewer with all tabs.
    Includes Mermaid Code, HTML Visualization, Interactive Editor (with paste-to-canvas), and Export.
    """
    
    try:
        # Read diagram content
        diagram_content = diagram_file.read_text(encoding='utf-8')
        
        # 🔥 FIX: Strip markdown code blocks (```mermaid) from content
        # Remove opening ```mermaid or ```
        diagram_content = diagram_content.strip()
        if diagram_content.startswith('```mermaid'):
            diagram_content = diagram_content[len('```mermaid'):].strip()
        elif diagram_content.startswith('```'):
            diagram_content = diagram_content[3:].strip()
        
        # Remove closing ```
        if diagram_content.endswith('```'):
            diagram_content = diagram_content[:-3].strip()
        
        # Show title
        st.markdown(f"#### 📈 {diagram_file.stem.replace('_', ' ').title()}")
        
        # Check if HTML version exists
        html_file = diagram_file.with_suffix('.html')
        has_html = html_file.exists()
        html_content = html_file.read_text(encoding='utf-8') if has_html else None
        
        # Create tabs
        if has_html:
            tab1, tab2, tab3, tab4 = st.tabs([
                "🎨 Mermaid Code",
                "🌐 HTML Visualization",
                "✏️ Interactive Editor",
                "📥 Export"
            ])
        else:
            tab1, tab3, tab4 = st.tabs([
                "🎨 Mermaid Code",
                "✏️ Interactive Editor",
                "📥 Export"
            ])
            tab2 = None
        
        # Tab 1: Mermaid Code (corrected)
        with tab1:
            # Show validation status for Mermaid code
            from components.mermaid_syntax_corrector import validate_mermaid_syntax
            is_valid, corrected_diagram, errors = validate_mermaid_syntax(diagram_content)
            
            if is_valid:
                st.success("✅ Valid Mermaid syntax")
            elif errors:
                st.info(f"ℹ️ Syntax was auto-corrected ({len(errors)} issues fixed)")
            
            # Display FULL diagram content (don't truncate!)
            display_content = diagram_content if diagram_content else corrected_diagram
            st.code(display_content, language="mermaid")
            
            # Show line count
            line_count = len(display_content.split('\n'))
            st.caption(f"📏 {line_count} lines | {len(display_content)} characters")
            
            # Mermaid Live link
            state = {
                "code": diagram_content,
                "mermaid": {"theme": "default"},
                "autoSync": True,
                "updateDiagram": True
            }
            state_json = json.dumps(state)
            compressed = zlib.compress(state_json.encode('utf-8'))
            encoded = base64.urlsafe_b64encode(compressed).decode('utf-8')
            live_link = f"https://mermaid.live/edit#pako:{encoded}"
            
            st.link_button("🔗 Open in Mermaid Live", live_link, use_container_width=True)
            st.caption("✅ Syntax automatically corrected")
        
        # Tab 2: HTML Visualization (if exists)
        if tab2 and has_html:
            with tab2:
                st.markdown("**🎨 LLM-Generated HTML Visualization** (Pure HTML, no Mermaid.js)")
                
                # Validate HTML content more flexibly
                is_valid_html = bool(
                    html_content and 
                    html_content.strip() and
                    ('<html' in html_content.lower() or '<!doctype html>' in html_content.lower()) and
                    '</html>' in html_content.lower()
                )
                
                if is_valid_html:
                    # Display HTML in iframe with error handling
                    try:
                        st.components.v1.html(html_content, height=700, scrolling=True)
                        st.success("✅ Generated by AI - Context-aware visualization")
                        st.caption("💡 This diagram uses actual codebase details from RAG context")
                    except Exception as e:
                        st.error(f"❌ Error rendering HTML: {str(e)}")
                        st.markdown("**🔍 HTML Source:**")
                        st.code(html_content[:1000] + "..." if len(html_content) > 1000 else html_content, language="html")
                else:
                    st.warning("⚠️ HTML visualization not available or invalid")
        
        # Tab 3: Interactive Editor with PASTE functionality
        with tab3:
            st.markdown("### ✏️ Interactive Visual Canvas Editor")
            st.caption("🎨 Drag-and-drop nodes, connect them, and see real-time Mermaid code generation!")
            
            # Paste area with Load to Canvas button
            paste_key = f"paste_mermaid_{diagram_file.stem}"
            if paste_key not in st.session_state:
                st.session_state[paste_key] = diagram_content
            
            st.markdown("**💡 Paste Mermaid code here to convert to visual nodes:**")
            pasted_code = st.text_area(
                "Paste Mermaid code (optional):",
                value=st.session_state[paste_key],
                height=120,
                key=f"paste_input_{diagram_file.stem}",
                help="Paste your Mermaid code and click 'Load to Canvas' to convert it to visual nodes"
            )
            
            col1, col2, col3 = st.columns([1, 1, 2])
            with col1:
                if st.button("🔄 Load to Canvas", key=f"load_paste_{diagram_file.stem}", type="primary"):
                    try:
                        # Strip markdown blocks from pasted code
                        clean_code = pasted_code.strip()
                        if clean_code.startswith('```mermaid'):
                            clean_code = clean_code[len('```mermaid'):].strip()
                        elif clean_code.startswith('```'):
                            clean_code = clean_code[3:].strip()
                        if clean_code.endswith('```'):
                            clean_code = clean_code[:-3].strip()
                        
                        # Debug: Show what we're parsing
                        lines = [l for l in clean_code.split('\n') if l.strip()]
                        diagram_type = "Unknown"
                        
                        # Comprehensive diagram type detection
                        if 'erDiagram' in clean_code:
                            diagram_type = "ERD (Entity-Relationship)"
                        elif 'classDiagram' in clean_code:
                            diagram_type = "Class Diagram"
                        elif 'stateDiagram' in clean_code:
                            diagram_type = "State Diagram"
                        elif 'sequenceDiagram' in clean_code:
                            diagram_type = "Sequence Diagram"
                        elif 'gantt' in clean_code.lower() and 'dateFormat' in clean_code:
                            diagram_type = "Gantt Chart"
                        elif 'pie' in clean_code.lower():
                            diagram_type = "Pie Chart"
                        elif 'journey' in clean_code.lower():
                            diagram_type = "User Journey"
                        elif 'gitGraph' in clean_code:
                            diagram_type = "Git Graph"
                        elif 'mindmap' in clean_code:
                            diagram_type = "Mindmap"
                        elif 'timeline' in clean_code:
                            diagram_type = "Timeline"
                        elif any(c4 in clean_code for c4 in ['C4Context', 'C4Container', 'C4Component', 'C4Dynamic']):
                            diagram_type = "C4 Diagram"
                        elif 'graph TD' in clean_code or 'graph LR' in clean_code or 'flowchart' in clean_code:
                            diagram_type = "Flowchart"
                        
                        st.info(f"📊 Detected: **{diagram_type}** ({len(clean_code)} chars, {len(lines)} lines)")
                        
                        # Update session state and parse to canvas
                        state_key = f"visual_editor_viewer_{diagram_file.stem}"
                        st.session_state[f'{state_key}_mermaid_code'] = clean_code
                        st.session_state[paste_key] = clean_code
                        
                        # Parse Mermaid code to create visual nodes
                        from components.visual_diagram_editor import VisualDiagramEditor
                        editor = VisualDiagramEditor()
                        editor._parse_mermaid_to_canvas(state_key, clean_code)
                        
                        # Show how many nodes were created
                        nodes_created = len(st.session_state.get(f'{state_key}_nodes', []))
                        edges_created = len(st.session_state.get(f'{state_key}_edges', []))
                        
                        if nodes_created > 0:
                            st.success(f"✅ Loaded {nodes_created} nodes and {edges_created} connections!")
                            st.info("👇 Switch to the **🎨 Canvas** tab below to see your nodes!")
                        else:
                            st.warning("⚠️ No nodes found in the code. Check your Mermaid syntax.")
                            st.write("**First 5 lines of code:**")
                            for i, line in enumerate(lines[:5]):
                                st.code(f"{i+1}: {line}", language="text")
                        
                        # Force a small delay before rerun to show the message
                        import time
                        time.sleep(0.5)
                        st.rerun()
                    except Exception as e:
                        st.error(f"❌ Error parsing code: {str(e)}")
                        import traceback
                        st.code(traceback.format_exc())
            
            with col2:
                if st.button("💾 Save to File", key=f"save_from_paste_{diagram_file.stem}"):
                    # Save pasted code directly to file
                    clean_code = pasted_code.strip()
                    if clean_code.startswith('```mermaid'):
                        clean_code = clean_code[len('```mermaid'):].strip()
                    elif clean_code.startswith('```'):
                        clean_code = clean_code[3:].strip()
                    if clean_code.endswith('```'):
                        clean_code = clean_code[:-3].strip()
                    
                    diagram_file.write_text(clean_code, encoding='utf-8')
                    st.success(f"✅ Saved to {diagram_file.name}")
            
            st.markdown("---")
            
            # Use the visual diagram editor with ALL tabs
            from components.visual_diagram_editor import render_visual_diagram_editor
            
            # Determine diagram type from filename
            diagram_type = "flowchart"  # default
            filename_lower = diagram_file.stem.lower()
            if "erd" in filename_lower or "entity" in filename_lower:
                diagram_type = "erd"
            elif "sequence" in filename_lower:
                diagram_type = "sequence"
            elif "class" in filename_lower:
                diagram_type = "class"
            
            # Render visual editor with ALL tabs (View, HTML Editor, Canvas, Download)
            render_visual_diagram_editor(
                diagram_type=diagram_type,
                initial_mermaid=diagram_content,
                key_suffix=f"viewer_{diagram_file.stem}",
                canvas_only=False  # Show ALL tabs!
            )
        
        # Tab 4: Export
        with tab4:
            st.markdown("**Export Diagram**")
            st.caption("Download in various formats")
            
            col1, col2 = st.columns(2)
            
            with col1:
                # Export Mermaid
                state_key = f"visual_editor_viewer_{diagram_file.stem}"
                export_code = st.session_state.get(f'{state_key}_mermaid_code', diagram_content)
                st.download_button(
                    label="📄 Download Mermaid (.mmd)",
                    data=export_code,
                    file_name=f"{diagram_file.stem}.mmd",
                    mime="text/plain",
                    key=f"export_mmd_{diagram_file.stem}"
                )
                
                # Export as Markdown
                markdown_content = f"# {diagram_file.stem.replace('_', ' ').title()}\n\n```mermaid\n{export_code}\n```"
                st.download_button(
                    label="📝 Download Markdown (.md)",
                    data=markdown_content,
                    file_name=f"{diagram_file.stem}.md",
                    mime="text/markdown",
                    key=f"export_md_{diagram_file.stem}"
                )
            
            with col2:
                # Export HTML (if exists)
                if has_html and html_content:
                    st.download_button(
                        label="🌐 Download HTML (.html)",
                        data=html_content,
                        file_name=f"{diagram_file.stem}.html",
                        mime="text/html",
                        key=f"export_html_{diagram_file.stem}"
                    )
                
                # Export JSON
                json_content = json.dumps({
                    "name": diagram_file.stem,
                    "mermaid": export_code,
                    "html": html_content if has_html else None,
                    "meeting_notes": meeting_notes
                }, indent=2)
                st.download_button(
                    label="📊 Download JSON (.json)",
                    data=json_content,
                    file_name=f"{diagram_file.stem}.json",
                    mime="application/json",
                    key=f"export_json_{diagram_file.stem}"
                )
    
    except Exception as e:
        st.error(f"❌ Error loading {diagram_file.name}: {str(e)}")
        import traceback
        # Don't use expander here to avoid nested expander errors
        st.markdown("**Error Details:**")
        st.code(traceback.format_exc(), language="python")

