"""
Interactive Diagram Viewer with Editor
Provides rich viewing and editing experience for diagrams
"""

import streamlit as st
import json
import zlib
import base64
from pathlib import Path
from typing import Optional
import asyncio


def _resolve_runtime_agent():
    """Reuse the active Architect.AI agent so editor generation respects provider/keys."""
    try:
        from app.app_v2 import resolve_provider_runtime, get_or_create_agent  # noqa: WPS433 inline import

        runtime_context, error = resolve_provider_runtime()
        if error or not runtime_context:
            st.warning(f"⚠️ Unable to use AI provider for editors: {error or 'no configuration'}")
            return None
        return get_or_create_agent(runtime_context["config"])
    except Exception as exc:  # pragma: no cover - defensive
        st.warning(f"⚠️ Could not reuse runtime agent ({exc})")
        return None


def render_diagram_viewer(diagram_file: Path, meeting_notes: str = ""):
    """
    Render interactive diagram viewer with tabs:
    1. Mermaid Code (corrected)
    2. HTML Visualization (LLM-generated, no Mermaid.js)
    3. Interactive Editor (edit + save)
    4. Export (all formats)
    """
    
    st.markdown(f"#### 📈 {diagram_file.stem.replace('_', ' ').title()}")
    
    try:
        # Read diagram content
        diagram_content = diagram_file.read_text(encoding='utf-8')
        
        # Check if HTML version exists
        html_file = diagram_file.with_suffix('.html')
        has_html = html_file.exists()
        html_content = html_file.read_text(encoding='utf-8') if has_html else None
        
        # Create tabs
        if has_html:
            tab1, tab2, tab3, tab4 = st.tabs([
                "🎨 Mermaid Code",
                "🌐 HTML Visualization",
                "✏️ Interactive Editor",
                "📥 Export"
            ])
        else:
            tab1, tab3, tab4 = st.tabs([
                "🎨 Mermaid Code",
                "✏️ Interactive Editor",
                "📥 Export"
            ])
            tab2 = None
        
        # Tab 1: Mermaid Code (corrected)
        with tab1:
            # Show validation status for Mermaid code
            from components.mermaid_syntax_corrector import validate_mermaid_syntax
            is_valid, corrected_diagram, errors = validate_mermaid_syntax(diagram_content)
            
            if is_valid:
                st.success("✅ Valid Mermaid syntax")
            elif errors:
                st.info(f"ℹ️ Syntax was auto-corrected ({len(errors)} issues fixed)")
            
            # Display corrected diagram (more helpful for users)
            st.code(corrected_diagram or diagram_content, language="mermaid")
            
            # Mermaid Live link
            state = {
                "code": diagram_content,
                "mermaid": {"theme": "default"},
                "autoSync": True,
                "updateDiagram": True
            }
            state_json = json.dumps(state)
            compressed = zlib.compress(state_json.encode('utf-8'))
            encoded = base64.urlsafe_b64encode(compressed).decode('utf-8')
            live_link = f"https://mermaid.live/edit#pako:{encoded}"
            
            st.link_button("🔗 Open in Mermaid Live", live_link, use_container_width=True)
            st.caption("✅ Syntax automatically corrected")
        
        # Tab 2: HTML Visualization (if exists)
        if tab2 and has_html:
            with tab2:
                st.markdown("**🎨 LLM-Generated HTML Visualization** (Pure HTML, no Mermaid.js)")
                
                # Validate HTML content more flexibly
                is_valid_html = bool(
                    html_content and 
                    html_content.strip() and
                    ('<html' in html_content.lower() or '<!doctype html>' in html_content.lower()) and
                    '</html>' in html_content.lower()
                )
                
                if is_valid_html:
                    # Display HTML in iframe with error handling
                    try:
                        st.components.v1.html(html_content, height=700, scrolling=True)
                        st.success("✅ Generated by Gemini AI - Context-aware visualization")
                        st.caption("💡 This diagram uses actual codebase details from RAG context")
                    except Exception as e:
                        st.error(f"❌ Error rendering HTML: {str(e)}")
                        with st.expander("🔍 View HTML Source"):
                            st.code(html_content[:1000] + "..." if len(html_content) > 1000 else html_content, language="html")
                else:
                    st.warning("⚠️ HTML visualization not available or invalid")
                    
                    # Show what we got instead
                    if html_content:
                        with st.expander("🔍 View Raw Output"):
                            st.code(html_content[:1000] + "..." if len(html_content) > 1000 else html_content)
                            st.caption("HTML appears to be malformed or incomplete")
                    else:
                        st.info("No HTML content was generated. The Gemini generation may have failed.")
                        st.caption("Try regenerating the diagram or check your API key.")
        
        # Tab 3: Interactive Editor
        with tab3:
            # Editor type selection
            editor_type = st.radio(
                "Choose Editor Type:",
                ["✏️ Code Editor", "🎨 Visual HTML Editor (AI-Generated)"],
                key=f"editor_type_{diagram_file.stem}",
                horizontal=True
            )
            
            if editor_type == "🎨 Visual HTML Editor (AI-Generated)":
                # AI-Generated Visual HTML Editor
                st.info("🎨 **AI-Generated Visual Diagram Editor**")
                st.caption("Gemini will generate an interactive HTML editor based on your diagram context")
                
                if st.button("🪄 Generate Visual Editor", key=f"gen_visual_{diagram_file.stem}", type="primary"):
                    with st.spinner("Generating visual editor with Gemini AI..."):
                        try:
                            from components.mermaid_html_renderer import mermaid_html_renderer

                            agent = _resolve_runtime_agent()
                            if agent is None:
                                st.error("❌ No AI agent available. Configure a provider in the sidebar and try again.")
                                return

                            meeting_summary = "\n".join(meeting_notes.strip().splitlines()[:5]) if meeting_notes else ""
                            editor_prompt = f"""
You are building an INTERACTIVE diagram editor for the Architect.AI workspace.

PROJECT CONTEXT:
- Diagram name: {diagram_file.stem}
- Meeting notes summary: {meeting_summary or 'N/A'}

MERMAID SOURCE (authoritative):
{diagram_content}

REQUIREMENTS:
1. Parse the Mermaid definition and render nodes/edges visually (drag + drop).
2. Provide an Inspector panel to edit node titles, descriptions, and connection labels.
3. Allow adding/removing nodes and edges in the UI with buttons.
4. Keep styling consistent with Architect.AI (dark gradient background, rounded cards, Segoe UI typography).
5. Include real-time Mermaid preview + "Export Mermaid" button that prints the updated definition.
6. Use vanilla HTML/CSS/JS (no external CDN). Embed everything in one document.
7. Persist edits in memory (e.g., using JSON structure) so users can make multiple adjustments before exporting.
8. Highlight differences compared to the original Mermaid whenever the preview updates.

OUTPUT: A single production-ready HTML document (doctype included) containing markup, styles, and scripts.
"""

                            async def generate_editor() -> str:
                                return await agent._call_ai(
                                    editor_prompt,
                                    "You are an expert frontend engineer delivering polished interactive editors."
                                )

                            editor_html = asyncio.run(generate_editor())
                            
                            # Clean HTML
                            if '```html' in editor_html:
                                editor_html = editor_html.split('```html')[1].split('```')[0]
                            elif '```' in editor_html:
                                editor_html = editor_html.split('```')[1].split('```')[0]
                            
                            # Ensure proper HTML structure
                            if not editor_html.strip().startswith('<!DOCTYPE'):
                                editor_html = f"<!DOCTYPE html>\n{editor_html}"

                            if '<html' not in editor_html.lower() or '</html>' not in editor_html.lower():
                                raise ValueError("Generated editor HTML is incomplete. Please try again.")
                            
                            # Save the editor HTML
                            editor_file = diagram_file.parent / f"{diagram_file.stem}_editor.html"
                            editor_file.write_text(editor_html, encoding='utf-8')
                            
                            st.success("✅ Visual editor generated!")
                            st.session_state[f'visual_editor_html_{diagram_file.stem}'] = editor_html
                            st.rerun()
                            
                        except Exception as e:
                            st.error(f"❌ Error generating visual editor: {str(e)}")
                            st.info("💡 Tip: Make sure you have an AI API key configured")
                
                # Show generated editor if it exists
                editor_key = f'visual_editor_html_{diagram_file.stem}'
                editor_file = diagram_file.parent / f"{diagram_file.stem}_editor.html"
                
                if editor_key in st.session_state or editor_file.exists():
                    st.markdown("---")
                    st.markdown("**🎨 Interactive Visual Editor:**")
                    
                    # Load HTML if not in session state
                    if editor_key not in st.session_state and editor_file.exists():
                        st.session_state[editor_key] = editor_file.read_text(encoding='utf-8')
                    
                    # Display the visual editor
                    if editor_key in st.session_state:
                        st.components.v1.html(st.session_state[editor_key], height=800, scrolling=True)
                        
                        col1, col2 = st.columns(2)
                        with col1:
                            if st.button("🔄 Regenerate Editor", key=f"regen_editor_{diagram_file.stem}"):
                                if editor_key in st.session_state:
                                    del st.session_state[editor_key]
                                if editor_file.exists():
                                    editor_file.unlink()
                                st.rerun()
                        with col2:
                            if st.button("📥 Download Editor HTML", key=f"dl_editor_{diagram_file.stem}"):
                                st.download_button(
                                    label="Download",
                                    data=st.session_state[editor_key],
                                    file_name=f"{diagram_file.stem}_editor.html",
                                    mime="text/html"
                                )
                else:
                    st.info("👆 Click 'Generate Visual Editor' to create an AI-powered interactive editor")
            
            else:  # Code Editor
                st.markdown("**Edit Diagram Code**")
                st.caption("Make changes below and save to update the diagram")
            
            # Editable text area (available regardless of editor type)
            edited_content = st.text_area(
                "Diagram Code:",
                value=diagram_content,
                height=400,
                key=f"editor_{diagram_file.stem}"
            )
            
            col1, col2, col3 = st.columns(3)
            
            with col1:
                if st.button("💾 Save Changes", key=f"save_{diagram_file.stem}", type="primary"):
                    try:
                        # Save edited content
                        diagram_file.write_text(edited_content, encoding='utf-8')
                        
                        # Regenerate HTML if it existed
                        if has_html:
                            from components.mermaid_html_renderer import mermaid_html_renderer
                            import asyncio
                            
                            with st.spinner("Regenerating HTML visualization..."):
                                try:
                                    new_html = asyncio.run(
                                    mermaid_html_renderer.generate_html_visualization_with_gemini(
                                        edited_content,
                                        meeting_notes,
                                        diagram_file.stem,
                                        agent=_resolve_runtime_agent()
                                    )
                                    )
                                    html_file.write_text(new_html, encoding='utf-8')
                                    st.success("✅ Diagram and HTML updated!")
                                except Exception as e:
                                    st.warning(f"⚠️ Diagram saved, but HTML regeneration failed: {str(e)}")
                        else:
                            st.success("✅ Diagram saved!")
                        
                        st.rerun()
                    except Exception as e:
                        st.error(f"❌ Error saving: {str(e)}")
            
            with col2:
                if st.button("🔄 Reset", key=f"reset_{diagram_file.stem}"):
                    st.rerun()
            
            with col3:
                if st.button("🎨 Generate HTML", key=f"gen_html_{diagram_file.stem}"):
                    from components.mermaid_html_renderer import mermaid_html_renderer
                    import asyncio
                    
                    with st.spinner("Generating HTML visualization..."):
                        try:
                            html_context_agent = _resolve_runtime_agent()
                            context_payload = ""
                            if html_context_agent and getattr(html_context_agent, 'enhanced_rag_context', None):
                                context_payload = getattr(html_context_agent.enhanced_rag_context, 'context_text', '') or ""
                            if not context_payload and html_context_agent:
                                context_payload = getattr(html_context_agent, 'rag_context', '') or ""
                            context_payload = context_payload or meeting_notes
                            new_html = asyncio.run(
                                mermaid_html_renderer.generate_html_visualization_with_gemini(
                                    edited_content,
                                    meeting_notes,
                                    diagram_file.stem,
                                    context_payload,
                                    agent=html_context_agent
                                )
                            )
                            html_file.write_text(new_html, encoding='utf-8')
                            st.success("✅ HTML generated!")
                            st.rerun()
                        except Exception as e:
                            st.error(f"❌ Error generating HTML: {str(e)}")
        
        # Tab 4: Export
        with tab4:
            st.markdown("**Export Diagram**")
            st.caption("Download in various formats")
            
            col1, col2 = st.columns(2)
            
            with col1:
                # Export Mermaid
                st.download_button(
                    label="📄 Download Mermaid (.mmd)",
                    data=diagram_content,
                    file_name=f"{diagram_file.stem}.mmd",
                    mime="text/plain",
                    key=f"export_mmd_{diagram_file.stem}"
                )
                
                # Export as Markdown
                markdown_content = f"# {diagram_file.stem.replace('_', ' ').title()}\n\n```mermaid\n{diagram_content}\n```"
                st.download_button(
                    label="📝 Download Markdown (.md)",
                    data=markdown_content,
                    file_name=f"{diagram_file.stem}.md",
                    mime="text/markdown",
                    key=f"export_md_{diagram_file.stem}"
                )
            
            with col2:
                # Export HTML (if exists)
                if has_html and html_content:
                    st.download_button(
                        label="🌐 Download HTML (.html)",
                        data=html_content,
                        file_name=f"{diagram_file.stem}.html",
                        mime="text/html",
                        key=f"export_html_{diagram_file.stem}"
                    )
                
                # Export JSON
                json_content = json.dumps({
                    "name": diagram_file.stem,
                    "mermaid": diagram_content,
                    "html": html_content if has_html else None,
                    "meeting_notes": meeting_notes
                }, indent=2)
                st.download_button(
                    label="📊 Download JSON (.json)",
                    data=json_content,
                    file_name=f"{diagram_file.stem}.json",
                    mime="application/json",
                    key=f"export_json_{diagram_file.stem}"
                )
            
            st.info("💡 **Tip:** Use Mermaid Live to export as PNG/SVG/PDF")
        
        st.divider()
    
    except Exception as e:
        st.error(f"Error loading {diagram_file.name}: {str(e)}")

