"""
Interactive Diagram Viewer with Editor
Provides rich viewing and editing experience for diagrams
"""

import streamlit as st
import json
import zlib
import base64
from pathlib import Path
from typing import Optional
from utils.async_utils import run_async


def _resolve_runtime_agent():
    """Reuse the active Architect.AI agent so editor generation respects provider/keys."""
    try:
        from app.app_v2 import resolve_provider_runtime, get_or_create_agent  # noqa: WPS433 inline import

        runtime_context, error = resolve_provider_runtime()
        if error or not runtime_context:
            st.warning(f"⚠️ Unable to use AI provider for editors: {error or 'no configuration'}")
            return None
        return get_or_create_agent(runtime_context["config"])
    except Exception as exc:  # pragma: no cover - defensive
        st.warning(f"⚠️ Could not reuse runtime agent ({exc})")
        return None


def render_diagram_viewer(diagram_file: Path, meeting_notes: str = ""):
    """
    Render interactive diagram viewer with tabs:
    1. Mermaid Code (corrected)
    2. HTML Visualization (LLM-generated, no Mermaid.js)
    3. Interactive Editor (edit + save)
    4. Export (all formats)
    """
    
    st.markdown(f"#### 📈 {diagram_file.stem.replace('_', ' ').title()}")
    
    try:
        # Read diagram content
        diagram_content = diagram_file.read_text(encoding='utf-8')
        
        # Check if HTML version exists
        html_file = diagram_file.with_suffix('.html')
        has_html = html_file.exists()
        html_content = html_file.read_text(encoding='utf-8') if has_html else None
        
        # Create tabs
        if has_html:
            tab1, tab2, tab3, tab4 = st.tabs([
                "🎨 Mermaid Code",
                "🌐 HTML Visualization",
                "✏️ Interactive Editor",
                "📥 Export"
            ])
        else:
            tab1, tab3, tab4 = st.tabs([
                "🎨 Mermaid Code",
                "✏️ Interactive Editor",
                "📥 Export"
            ])
            tab2 = None
        
        # Tab 1: Mermaid Code (corrected)
        with tab1:
            # Show validation status for Mermaid code
            from components.mermaid_syntax_corrector import validate_mermaid_syntax
            is_valid, corrected_diagram, errors = validate_mermaid_syntax(diagram_content)
            
            if is_valid:
                st.success("✅ Valid Mermaid syntax")
            elif errors:
                st.info(f"ℹ️ Syntax was auto-corrected ({len(errors)} issues fixed)")
            
            # Display corrected diagram (more helpful for users)
            st.code(corrected_diagram or diagram_content, language="mermaid")
            
            # Mermaid Live link
            state = {
                "code": diagram_content,
                "mermaid": {"theme": "default"},
                "autoSync": True,
                "updateDiagram": True
            }
            state_json = json.dumps(state)
            compressed = zlib.compress(state_json.encode('utf-8'))
            encoded = base64.urlsafe_b64encode(compressed).decode('utf-8')
            live_link = f"https://mermaid.live/edit#pako:{encoded}"
            
            st.link_button("🔗 Open in Mermaid Live", live_link, use_container_width=True)
            st.caption("✅ Syntax automatically corrected")
        
        # Tab 2: HTML Visualization (if exists)
        if tab2 and has_html:
            with tab2:
                st.markdown("**🎨 LLM-Generated HTML Visualization** (Pure HTML, no Mermaid.js)")
                
                # Validate HTML content more flexibly
                is_valid_html = bool(
                    html_content and 
                    html_content.strip() and
                    ('<html' in html_content.lower() or '<!doctype html>' in html_content.lower()) and
                    '</html>' in html_content.lower()
                )
                
                if is_valid_html:
                    # Display HTML in iframe with error handling
                    try:
                        st.components.v1.html(html_content, height=700, scrolling=True)
                        st.success("✅ Generated by Gemini AI - Context-aware visualization")
                        st.caption("💡 This diagram uses actual codebase details from RAG context")
                    except Exception as e:
                        st.error(f"❌ Error rendering HTML: {str(e)}")
                        st.markdown("**🔍 HTML Source:**")
                        st.code(html_content[:1000] + "..." if len(html_content) > 1000 else html_content, language="html")
                else:
                    st.warning("⚠️ HTML visualization not available or invalid")
                    
                    # Show what we got instead
                    if html_content:
                        st.markdown("**🔍 Raw Output:**")
                        st.code(html_content[:1000] + "..." if len(html_content) > 1000 else html_content)
                        st.caption("HTML appears to be malformed or incomplete")
                    else:
                        st.info("No HTML content was generated. The Gemini generation may have failed.")
                        st.caption("Try regenerating the diagram or check your API key.")
        
                # Tab 3: Interactive Editor
        with tab3:
            st.markdown("### ✏️ Interactive Mermaid Canvas Editor")
            st.caption("Edit the diagram code and see live preview. Save your changes when done.")
            
            # Use our own mermaid_editor component
            from components.mermaid_editor import render_mermaid_editor
            
            edited_content = render_mermaid_editor(
                initial_code=diagram_content,
                key=f"canvas_editor_{diagram_file.stem}"
            )
            
            # Action buttons below the editor
            st.markdown("---")
            col1, col2, col3 = st.columns(3)
        
        # Tab 4: Export
        with tab4:
            st.markdown("**Export Diagram**")
            st.caption("Download in various formats")
            
            col1, col2 = st.columns(2)
            
            with col1:
                # Export Mermaid
                st.download_button(
                    label="📄 Download Mermaid (.mmd)",
                    data=diagram_content,
                    file_name=f"{diagram_file.stem}.mmd",
                    mime="text/plain",
                    key=f"export_mmd_{diagram_file.stem}"
                )
                
                # Export as Markdown
                markdown_content = f"# {diagram_file.stem.replace('_', ' ').title()}\n\n```mermaid\n{diagram_content}\n```"
                st.download_button(
                    label="📝 Download Markdown (.md)",
                    data=markdown_content,
                    file_name=f"{diagram_file.stem}.md",
                    mime="text/markdown",
                    key=f"export_md_{diagram_file.stem}"
                )
            
            with col2:
                # Export HTML (if exists)
                if has_html and html_content:
                    st.download_button(
                        label="🌐 Download HTML (.html)",
                        data=html_content,
                        file_name=f"{diagram_file.stem}.html",
                        mime="text/html",
                        key=f"export_html_{diagram_file.stem}"
                    )
                
                # Export JSON
                json_content = json.dumps({
                    "name": diagram_file.stem,
                    "mermaid": diagram_content,
                    "html": html_content if has_html else None,
                    "meeting_notes": meeting_notes
                }, indent=2)
                st.download_button(
                    label="📊 Download JSON (.json)",
                    data=json_content,
                    file_name=f"{diagram_file.stem}.json",
                    mime="application/json",
                    key=f"export_json_{diagram_file.stem}"
                )
            
            st.info("💡 **Tip:** Use Mermaid Live to export as PNG/SVG/PDF")
        
        st.divider()
    
    except Exception as e:
        st.error(f"Error loading {diagram_file.name}: {str(e)}")

