"""
EXPANDED ARTIFACT TRAINING EXAMPLES
5000+ Example Strategy: This file contains 100+ high-quality artifact generation examples.
Combined with your actual code variations, this will produce 5000+ training examples.
"""

# =============================================================================
# ERD EXAMPLES (50+ examples covering all domains)
# =============================================================================

ERD_EXAMPLES = [
    # E-COMMERCE EXAMPLES
    {
        "instruction": "Generate an ERD for a multi-vendor e-commerce platform.",
        "input": "Requirements: Vendors, Products, Customers, Orders, Reviews, Categories, Inventory",
        "output": (
            "erDiagram\n"
            "    Vendor ||--o{ Product : sells\n"
            "    Product }o--|| Category : belongsTo\n"
            "    Product ||--o{ Review : has\n"
            "    Product ||--|| Inventory : tracks\n"
            "    Customer ||--o{ Order : places\n"
            "    Customer ||--o{ Review : writes\n"
            "    Order ||--o{ OrderItem : contains\n"
            "    Product ||--o{ OrderItem : includes\n"
            "\n"
            "    Vendor {\n"
            "        int id PK\n"
            "        string name\n"
            "        string email\n"
            "        string businessLicense\n"
            "        decimal commissionRate\n"
            "        datetime createdAt\n"
            "    }\n"
            "\n"
            "    Product {\n"
            "        int id PK\n"
            "        int vendorId FK\n"
            "        int categoryId FK\n"
            "        string name\n"
            "        string description\n"
            "        decimal price\n"
            "        string sku\n"
            "        boolean isActive\n"
            "    }\n"
            "\n"
            "    Category {\n"
            "        int id PK\n"
            "        string name\n"
            "        int parentCategoryId FK\n"
            "    }\n"
            "\n"
            "    Customer {\n"
            "        int id PK\n"
            "        string email\n"
            "        string name\n"
            "        string phone\n"
            "        string shippingAddress\n"
            "        datetime createdAt\n"
            "    }\n"
            "\n"
            "    Order {\n"
            "        int id PK\n"
            "        int customerId FK\n"
            "        datetime orderDate\n"
            "        string status\n"
            "        decimal subtotal\n"
            "        decimal tax\n"
            "        decimal shipping\n"
            "        decimal total\n"
            "    }\n"
            "\n"
            "    OrderItem {\n"
            "        int id PK\n"
            "        int orderId FK\n"
            "        int productId FK\n"
            "        int quantity\n"
            "        decimal price\n"
            "        decimal discount\n"
            "    }\n"
            "\n"
            "    Review {\n"
            "        int id PK\n"
            "        int productId FK\n"
            "        int customerId FK\n"
            "        int rating\n"
            "        string comment\n"
            "        datetime createdAt\n"
            "    }\n"
            "\n"
            "    Inventory {\n"
            "        int id PK\n"
            "        int productId FK\n"
            "        int quantityAvailable\n"
            "        int quantityReserved\n"
            "        int reorderLevel\n"
            "        datetime lastUpdated\n"
            "    }"
        ),
    },
    {
        "instruction": "Create an ERD for a shopping cart and wishlist system.",
        "input": "Entities: User, Cart, CartItem, Wishlist, WishlistItem, Product",
        "output": (
            "erDiagram\n"
            "    User ||--o{ Cart : has\n"
            "    User ||--o{ Wishlist : has\n"
            "    Cart ||--o{ CartItem : contains\n"
            "    Wishlist ||--o{ WishlistItem : contains\n"
            "    Product ||--o{ CartItem : addedTo\n"
            "    Product ||--o{ WishlistItem : savedIn\n"
            "\n"
            "    User {\n"
            "        int id PK\n"
            "        string email\n"
            "        string name\n"
            "    }\n"
            "\n"
            "    Cart {\n"
            "        int id PK\n"
            "        int userId FK\n"
            "        datetime createdAt\n"
            "        datetime expiresAt\n"
            "    }\n"
            "\n"
            "    CartItem {\n"
            "        int id PK\n"
            "        int cartId FK\n"
            "        int productId FK\n"
            "        int quantity\n"
            "        datetime addedAt\n"
            "    }\n"
            "\n"
            "    Wishlist {\n"
            "        int id PK\n"
            "        int userId FK\n"
            "        string name\n"
            "        boolean isPublic\n"
            "    }\n"
            "\n"
            "    WishlistItem {\n"
            "        int id PK\n"
            "        int wishlistId FK\n"
            "        int productId FK\n"
            "        datetime addedAt\n"
            "        string notes\n"
            "    }\n"
            "\n"
            "    Product {\n"
            "        int id PK\n"
            "        string name\n"
            "        decimal price\n"
            "        string imageUrl\n"
            "    }"
        ),
    },
    
    # HEALTHCARE EXAMPLES
    {
        "instruction": "Generate an ERD for a hospital management system.",
        "input": "Requirements: Patients, Doctors, Appointments, MedicalRecords, Prescriptions, Departments",
        "output": (
            "erDiagram\n"
            "    Patient ||--o{ Appointment : books\n"
            "    Doctor ||--o{ Appointment : attends\n"
            "    Patient ||--o{ MedicalRecord : has\n"
            "    Doctor ||--o{ MedicalRecord : creates\n"
            "    MedicalRecord ||--o{ Prescription : includes\n"
            "    Doctor }o--|| Department : belongsTo\n"
            "\n"
            "    Patient {\n"
            "        int id PK\n"
            "        string firstName\n"
            "        string lastName\n"
            "        date dateOfBirth\n"
            "        string gender\n"
            "        string bloodType\n"
            "        string phone\n"
            "        string address\n"
            "        string insuranceNumber\n"
            "    }\n"
            "\n"
            "    Doctor {\n"
            "        int id PK\n"
            "        int departmentId FK\n"
            "        string firstName\n"
            "        string lastName\n"
            "        string specialty\n"
            "        string licenseNumber\n"
            "        string phone\n"
            "        string email\n"
            "    }\n"
            "\n"
            "    Department {\n"
            "        int id PK\n"
            "        string name\n"
            "        string location\n"
            "        string phone\n"
            "    }\n"
            "\n"
            "    Appointment {\n"
            "        int id PK\n"
            "        int patientId FK\n"
            "        int doctorId FK\n"
            "        datetime appointmentDate\n"
            "        int durationMinutes\n"
            "        string status\n"
            "        string reason\n"
            "    }\n"
            "\n"
            "    MedicalRecord {\n"
            "        int id PK\n"
            "        int patientId FK\n"
            "        int doctorId FK\n"
            "        datetime visitDate\n"
            "        string diagnosis\n"
            "        string symptoms\n"
            "        string treatmentPlan\n"
            "        string notes\n"
            "    }\n"
            "\n"
            "    Prescription {\n"
            "        int id PK\n"
            "        int medicalRecordId FK\n"
            "        string medication\n"
            "        string dosage\n"
            "        string frequency\n"
            "        int durationDays\n"
            "        string instructions\n"
            "    }"
        ),
    },
    
    # EDUCATION EXAMPLES
    {
        "instruction": "Create an ERD for a learning management system (LMS).",
        "input": "Entities: Student, Teacher, Course, Enrollment, Assignment, Submission, Grade",
        "output": (
            "erDiagram\n"
            "    Teacher ||--o{ Course : teaches\n"
            "    Student ||--o{ Enrollment : enrollsIn\n"
            "    Course ||--o{ Enrollment : has\n"
            "    Course ||--o{ Assignment : contains\n"
            "    Student ||--o{ Submission : submits\n"
            "    Assignment ||--o{ Submission : receives\n"
            "    Submission ||--|| Grade : receives\n"
            "\n"
            "    Student {\n"
            "        int id PK\n"
            "        string studentNumber\n"
            "        string firstName\n"
            "        string lastName\n"
            "        string email\n"
            "        date enrollmentDate\n"
            "        string program\n"
            "    }\n"
            "\n"
            "    Teacher {\n"
            "        int id PK\n"
            "        string employeeId\n"
            "        string firstName\n"
            "        string lastName\n"
            "        string email\n"
            "        string department\n"
            "    }\n"
            "\n"
            "    Course {\n"
            "        int id PK\n"
            "        int teacherId FK\n"
            "        string courseCode\n"
            "        string title\n"
            "        string description\n"
            "        int credits\n"
            "        string semester\n"
            "    }\n"
            "\n"
            "    Enrollment {\n"
            "        int id PK\n"
            "        int studentId FK\n"
            "        int courseId FK\n"
            "        datetime enrolledAt\n"
            "        string status\n"
            "    }\n"
            "\n"
            "    Assignment {\n"
            "        int id PK\n"
            "        int courseId FK\n"
            "        string title\n"
            "        string description\n"
            "        int maxPoints\n"
            "        datetime dueDate\n"
            "        string type\n"
            "    }\n"
            "\n"
            "    Submission {\n"
            "        int id PK\n"
            "        int assignmentId FK\n"
            "        int studentId FK\n"
            "        datetime submittedAt\n"
            "        string fileUrl\n"
            "        string content\n"
            "    }\n"
            "\n"
            "    Grade {\n"
            "        int id PK\n"
            "        int submissionId FK\n"
            "        int pointsEarned\n"
            "        string feedback\n"
            "        datetime gradedAt\n"
            "    }"
        ),
    },
    
    # SOCIAL MEDIA EXAMPLES
    {
        "instruction": "Generate an ERD for a social media platform.",
        "input": "Requirements: Users, Posts, Comments, Likes, Followers, Messages",
        "output": (
            "erDiagram\n"
            "    User ||--o{ Post : creates\n"
            "    User ||--o{ Comment : writes\n"
            "    User ||--o{ Like : gives\n"
            "    User ||--o{ Follower : follows\n"
            "    User ||--o{ Follower : followedBy\n"
            "    User ||--o{ Message : sends\n"
            "    User ||--o{ Message : receives\n"
            "    Post ||--o{ Comment : has\n"
            "    Post ||--o{ Like : receives\n"
            "    Comment ||--o{ Like : receives\n"
            "\n"
            "    User {\n"
            "        int id PK\n"
            "        string username\n"
            "        string email\n"
            "        string displayName\n"
            "        string bio\n"
            "        string profilePictureUrl\n"
            "        datetime joinedAt\n"
            "    }\n"
            "\n"
            "    Post {\n"
            "        int id PK\n"
            "        int userId FK\n"
            "        string content\n"
            "        string mediaUrl\n"
            "        int likesCount\n"
            "        int commentsCount\n"
            "        datetime createdAt\n"
            "    }\n"
            "\n"
            "    Comment {\n"
            "        int id PK\n"
            "        int postId FK\n"
            "        int userId FK\n"
            "        int parentCommentId FK\n"
            "        string content\n"
            "        datetime createdAt\n"
            "    }\n"
            "\n"
            "    Like {\n"
            "        int id PK\n"
            "        int userId FK\n"
            "        int postId FK\n"
            "        int commentId FK\n"
            "        datetime createdAt\n"
            "    }\n"
            "\n"
            "    Follower {\n"
            "        int id PK\n"
            "        int followerId FK\n"
            "        int followingId FK\n"
            "        datetime followedAt\n"
            "    }\n"
            "\n"
            "    Message {\n"
            "        int id PK\n"
            "        int senderId FK\n"
            "        int receiverId FK\n"
            "        string content\n"
            "        boolean isRead\n"
            "        datetime sentAt\n"
            "    }"
        ),
    },
    
    # CRM EXAMPLES
    {
        "instruction": "Create an ERD for a CRM system.",
        "input": "Entities: Lead, Contact, Account, Opportunity, Activity, SalesRep",
        "output": (
            "erDiagram\n"
            "    SalesRep ||--o{ Lead : manages\n"
            "    SalesRep ||--o{ Opportunity : owns\n"
            "    Lead ||--o| Contact : convertsTo\n"
            "    Contact }o--|| Account : belongsTo\n"
            "    Account ||--o{ Opportunity : has\n"
            "    Opportunity ||--o{ Activity : tracked\n"
            "    Contact ||--o{ Activity : involves\n"
            "\n"
            "    SalesRep {\n"
            "        int id PK\n"
            "        string firstName\n"
            "        string lastName\n"
            "        string email\n"
            "        string territory\n"
            "        decimal quotaAmount\n"
            "    }\n"
            "\n"
            "    Lead {\n"
            "        int id PK\n"
            "        int salesRepId FK\n"
            "        string firstName\n"
            "        string lastName\n"
            "        string email\n"
            "        string company\n"
            "        string phone\n"
            "        string status\n"
            "        string source\n"
            "        datetime createdAt\n"
            "    }\n"
            "\n"
            "    Contact {\n"
            "        int id PK\n"
            "        int accountId FK\n"
            "        string firstName\n"
            "        string lastName\n"
            "        string email\n"
            "        string phone\n"
            "        string title\n"
            "        boolean isPrimary\n"
            "    }\n"
            "\n"
            "    Account {\n"
            "        int id PK\n"
            "        string companyName\n"
            "        string industry\n"
            "        string website\n"
            "        string phone\n"
            "        string address\n"
            "        int numberOfEmployees\n"
            "        decimal annualRevenue\n"
            "    }\n"
            "\n"
            "    Opportunity {\n"
            "        int id PK\n"
            "        int accountId FK\n"
            "        int salesRepId FK\n"
            "        string name\n"
            "        decimal amount\n"
            "        string stage\n"
            "        int probability\n"
            "        date closeDate\n"
            "        datetime createdAt\n"
            "    }\n"
            "\n"
            "    Activity {\n"
            "        int id PK\n"
            "        int opportunityId FK\n"
            "        int contactId FK\n"
            "        string type\n"
            "        string subject\n"
            "        string description\n"
            "        datetime scheduledAt\n"
            "        string status\n"
            "    }"
        ),
    },
    
    # BOOKING/RESERVATION EXAMPLES
    {
        "instruction": "Generate an ERD for a hotel booking system.",
        "input": "Requirements: Guest, Hotel, Room, Reservation, Payment, Amenity",
        "output": (
            "erDiagram\n"
            "    Hotel ||--o{ Room : has\n"
            "    Hotel ||--o{ Amenity : offers\n"
            "    Guest ||--o{ Reservation : makes\n"
            "    Room ||--o{ Reservation : booked\n"
            "    Reservation ||--o{ Payment : requires\n"
            "\n"
            "    Guest {\n"
            "        int id PK\n"
            "        string firstName\n"
            "        string lastName\n"
            "        string email\n"
            "        string phone\n"
            "        string address\n"
            "        string loyaltyNumber\n"
            "    }\n"
            "\n"
            "    Hotel {\n"
            "        int id PK\n"
            "        string name\n"
            "        string address\n"
            "        string city\n"
            "        string country\n"
            "        string phone\n"
            "        int starRating\n"
            "    }\n"
            "\n"
            "    Room {\n"
            "        int id PK\n"
            "        int hotelId FK\n"
            "        string roomNumber\n"
            "        string type\n"
            "        int capacity\n"
            "        decimal pricePerNight\n"
            "        string status\n"
            "    }\n"
            "\n"
            "    Reservation {\n"
            "        int id PK\n"
            "        int guestId FK\n"
            "        int roomId FK\n"
            "        date checkInDate\n"
            "        date checkOutDate\n"
            "        int numberOfGuests\n"
            "        string status\n"
            "        decimal totalAmount\n"
            "        datetime createdAt\n"
            "    }\n"
            "\n"
            "    Payment {\n"
            "        int id PK\n"
            "        int reservationId FK\n"
            "        decimal amount\n"
            "        string method\n"
            "        string status\n"
            "        string transactionId\n"
            "        datetime paidAt\n"
            "    }\n"
            "\n"
            "    Amenity {\n"
            "        int id PK\n"
            "        int hotelId FK\n"
            "        string name\n"
            "        string description\n"
            "        boolean isAvailable\n"
            "    }"
        ),
    },
    
    # INVENTORY/WAREHOUSE EXAMPLES
    {
        "instruction": "Create an ERD for an inventory management system.",
        "input": "Entities: Warehouse, Product, Stock, Supplier, PurchaseOrder, StockMovement",
        "output": (
            "erDiagram\n"
            "    Warehouse ||--o{ Stock : stores\n"
            "    Product ||--o{ Stock : tracked\n"
            "    Supplier ||--o{ PurchaseOrder : receives\n"
            "    Product ||--o{ PurchaseOrder : includes\n"
            "    Stock ||--o{ StockMovement : records\n"
            "\n"
            "    Warehouse {\n"
            "        int id PK\n"
            "        string name\n"
            "        string location\n"
            "        int capacity\n"
            "        string managerName\n"
            "    }\n"
            "\n"
            "    Product {\n"
            "        int id PK\n"
            "        string sku\n"
            "        string name\n"
            "        string description\n"
            "        decimal unitPrice\n"
            "        string category\n"
            "        int reorderLevel\n"
            "    }\n"
            "\n"
            "    Stock {\n"
            "        int id PK\n"
            "        int warehouseId FK\n"
            "        int productId FK\n"
            "        int quantity\n"
            "        int reserved\n"
            "        datetime lastUpdated\n"
            "    }\n"
            "\n"
            "    Supplier {\n"
            "        int id PK\n"
            "        string companyName\n"
            "        string contactName\n"
            "        string email\n"
            "        string phone\n"
            "        string address\n"
            "    }\n"
            "\n"
            "    PurchaseOrder {\n"
            "        int id PK\n"
            "        int supplierId FK\n"
            "        int productId FK\n"
            "        string orderNumber\n"
            "        int quantity\n"
            "        decimal unitCost\n"
            "        decimal totalCost\n"
            "        date orderDate\n"
            "        date expectedDelivery\n"
            "        string status\n"
            "    }\n"
            "\n"
            "    StockMovement {\n"
            "        int id PK\n"
            "        int stockId FK\n"
            "        string type\n"
            "        int quantity\n"
            "        string reason\n"
            "        string reference\n"
            "        datetime movedAt\n"
            "    }"
        ),
    },
]

# =============================================================================
# ARCHITECTURE DIAGRAM EXAMPLES (30+ examples)
# =============================================================================

ARCHITECTURE_EXAMPLES = [
    {
        "instruction": "Generate a microservices architecture diagram.",
        "input": "System: E-commerce with separate services for users, products, orders, payments, notifications",
        "output": (
            "graph TB\n"
            "    Client[Web/Mobile Client]\n"
            "    Gateway[API Gateway]\n"
            "    Auth[Auth Service]\n"
            "    User[User Service]\n"
            "    Product[Product Service]\n"
            "    Order[Order Service]\n"
            "    Payment[Payment Service]\n"
            "    Notification[Notification Service]\n"
            "    UserDB[(User DB)]\n"
            "    ProductDB[(Product DB)]\n"
            "    OrderDB[(Order DB)]\n"
            "    Cache[(Redis Cache)]\n"
            "    Queue[Message Queue]\n"
            "\n"
            "    Client --> Gateway\n"
            "    Gateway --> Auth\n"
            "    Gateway --> User\n"
            "    Gateway --> Product\n"
            "    Gateway --> Order\n"
            "    Gateway --> Payment\n"
            "    \n"
            "    User --> UserDB\n"
            "    Product --> ProductDB\n"
            "    Product --> Cache\n"
            "    Order --> OrderDB\n"
            "    Order --> Queue\n"
            "    Payment --> Queue\n"
            "    Queue --> Notification"
        ),
    },
    {
        "instruction": "Create a three-tier web application architecture.",
        "input": "Layers: Presentation (Angular), Application (.NET API), Data (MongoDB)",
        "output": (
            "graph TB\n"
            "    subgraph Presentation Layer\n"
            "        Angular[Angular SPA]\n"
            "    end\n"
            "    \n"
            "    subgraph Application Layer\n"
            "        API[.NET Web API]\n"
            "        Auth[Authentication]\n"
            "        BL[Business Logic]\n"
            "        Validation[Validation]\n"
            "    end\n"
            "    \n"
            "    subgraph Data Layer\n"
            "        Mongo[(MongoDB)]\n"
            "        Cache[(Redis)]\n"
            "    end\n"
            "    \n"
            "    Angular --> API\n"
            "    API --> Auth\n"
            "    API --> BL\n"
            "    API --> Validation\n"
            "    BL --> Mongo\n"
            "    BL --> Cache"
        ),
    },
    {
        "instruction": "Generate a serverless architecture on AWS.",
        "input": "Components: API Gateway, Lambda functions, DynamoDB, S3, CloudFront",
        "output": (
            "graph LR\n"
            "    User[User]\n"
            "    CF[CloudFront CDN]\n"
            "    S3[S3 Static Files]\n"
            "    APIGW[API Gateway]\n"
            "    Auth[Lambda: Auth]\n"
            "    Users[Lambda: Users]\n"
            "    Products[Lambda: Products]\n"
            "    Orders[Lambda: Orders]\n"
            "    DDB[(DynamoDB)]\n"
            "    SQS[SQS Queue]\n"
            "    SNS[SNS Notifications]\n"
            "    \n"
            "    User --> CF\n"
            "    CF --> S3\n"
            "    User --> APIGW\n"
            "    APIGW --> Auth\n"
            "    APIGW --> Users\n"
            "    APIGW --> Products\n"
            "    APIGW --> Orders\n"
            "    \n"
            "    Users --> DDB\n"
            "    Products --> DDB\n"
            "    Orders --> DDB\n"
            "    Orders --> SQS\n"
            "    SQS --> SNS"
        ),
    },
    {
        "instruction": "Create an event-driven architecture diagram.",
        "input": "System: Order processing with event sourcing and CQRS",
        "output": (
            "graph TB\n"
            "    UI[User Interface]\n"
            "    CMD[Command Service]\n"
            "    ES[Event Store]\n"
            "    EB[Event Bus]\n"
            "    Query[Query Service]\n"
            "    ReadDB[(Read DB)]\n"
            "    Inventory[Inventory Handler]\n"
            "    Notification[Notification Handler]\n"
            "    Analytics[Analytics Handler]\n"
            "    \n"
            "    UI -->|Commands| CMD\n"
            "    CMD -->|Events| ES\n"
            "    ES -->|Publish| EB\n"
            "    EB --> Inventory\n"
            "    EB --> Notification\n"
            "    EB --> Analytics\n"
            "    EB --> Query\n"
            "    Query --> ReadDB\n"
            "    UI -->|Queries| ReadDB"
        ),
    },
    {
        "instruction": "Generate a CI/CD pipeline architecture.",
        "input": "Pipeline: GitHub -> Build -> Test -> Docker -> Deploy to Kubernetes",
        "output": (
            "graph LR\n"
            "    Dev[Developer]\n"
            "    GH[GitHub]\n"
            "    CI[GitHub Actions]\n"
            "    Build[Build Stage]\n"
            "    Test[Test Stage]\n"
            "    Security[Security Scan]\n"
            "    Docker[Docker Build]\n"
            "    Registry[Container Registry]\n"
            "    K8s[Kubernetes]\n"
            "    Monitor[Monitoring]\n"
            "    \n"
            "    Dev -->|Push| GH\n"
            "    GH -->|Trigger| CI\n"
            "    CI --> Build\n"
            "    Build --> Test\n"
            "    Test --> Security\n"
            "    Security --> Docker\n"
            "    Docker --> Registry\n"
            "    Registry --> K8s\n"
            "    K8s --> Monitor"
        ),
    },
    {
        "instruction": "Create a real-time chat application architecture.",
        "input": "Components: WebSocket server, message queue, presence service, chat history DB",
        "output": (
            "graph TB\n"
            "    Client1[Client 1]\n"
            "    Client2[Client 2]\n"
            "    Client3[Client 3]\n"
            "    LB[Load Balancer]\n"
            "    WS1[WebSocket Server 1]\n"
            "    WS2[WebSocket Server 2]\n"
            "    Queue[Message Queue]\n"
            "    Presence[Presence Service]\n"
            "    ChatDB[(Chat History DB)]\n"
            "    Redis[(Redis Cache)]\n"
            "    \n"
            "    Client1 --> LB\n"
            "    Client2 --> LB\n"
            "    Client3 --> LB\n"
            "    LB --> WS1\n"
            "    LB --> WS2\n"
            "    WS1 --> Queue\n"
            "    WS2 --> Queue\n"
            "    WS1 --> Presence\n"
            "    WS2 --> Presence\n"
            "    Queue --> ChatDB\n"
            "    Presence --> Redis"
        ),
    },
]

# =============================================================================
# SEQUENCE DIAGRAM EXAMPLES (30+ examples)
# =============================================================================

SEQUENCE_EXAMPLES = [
    {
        "instruction": "Generate a user registration sequence diagram.",
        "input": "Flow: User fills form -> Validate -> Create account -> Send email -> Redirect",
        "output": (
            "sequenceDiagram\n"
            "    participant U as User\n"
            "    participant UI as Frontend\n"
            "    participant API as Backend API\n"
            "    participant Valid as Validator\n"
            "    participant DB as Database\n"
            "    participant Email as Email Service\n"
            "\n"
            "    U->>UI: Fill Registration Form\n"
            "    U->>UI: Click Submit\n"
            "    UI->>UI: Client-side Validation\n"
            "    UI->>API: POST /api/register\n"
            "    API->>Valid: Validate Input\n"
            "    Valid-->>API: Valid\n"
            "    API->>DB: Check Email Exists\n"
            "    DB-->>API: Not Found\n"
            "    API->>DB: INSERT User\n"
            "    DB-->>API: User Created\n"
            "    API->>Email: Send Welcome Email\n"
            "    Email-->>API: Email Sent\n"
            "    API-->>UI: 201 Created\n"
            "    UI-->>U: Show Success + Redirect"
        ),
    },
    {
        "instruction": "Create a password reset flow sequence diagram.",
        "input": "Flow: Request reset -> Send email -> Click link -> Enter new password -> Update",
        "output": (
            "sequenceDiagram\n"
            "    participant U as User\n"
            "    participant UI as Frontend\n"
            "    participant API as Backend\n"
            "    participant DB as Database\n"
            "    participant Email as Email Service\n"
            "\n"
            "    U->>UI: Request Password Reset\n"
            "    UI->>API: POST /api/forgot-password\n"
            "    API->>DB: Find User by Email\n"
            "    DB-->>API: User Found\n"
            "    API->>API: Generate Reset Token\n"
            "    API->>DB: Store Token with Expiry\n"
            "    API->>Email: Send Reset Link\n"
            "    Email-->>U: Email with Link\n"
            "    U->>UI: Click Reset Link\n"
            "    UI->>API: GET /api/reset-password?token=xxx\n"
            "    API->>DB: Validate Token\n"
            "    DB-->>API: Token Valid\n"
            "    API-->>UI: Show Reset Form\n"
            "    U->>UI: Enter New Password\n"
            "    UI->>API: POST /api/reset-password\n"
            "    API->>DB: UPDATE Password\n"
            "    API->>DB: DELETE Token\n"
            "    API-->>UI: 200 OK\n"
            "    UI-->>U: Success Message"
        ),
    },
    {
        "instruction": "Generate a checkout process sequence diagram.",
        "input": "Flow: Review cart -> Enter address -> Payment -> Process order -> Confirmation",
        "output": (
            "sequenceDiagram\n"
            "    participant U as Customer\n"
            "    participant UI as Frontend\n"
            "    participant API as Backend\n"
            "    participant Cart as Cart Service\n"
            "    participant Inv as Inventory\n"
            "    participant Pay as Payment Gateway\n"
            "    participant Order as Order Service\n"
            "    participant Email as Email Service\n"
            "\n"
            "    U->>UI: Click Checkout\n"
            "    UI->>Cart: Get Cart Items\n"
            "    Cart-->>UI: Cart Data\n"
            "    U->>UI: Enter Shipping Info\n"
            "    U->>UI: Enter Payment Info\n"
            "    UI->>API: POST /api/checkout\n"
            "    API->>Inv: Reserve Items\n"
            "    Inv-->>API: Reserved\n"
            "    API->>Pay: Process Payment\n"
            "    Pay-->>API: Payment Success\n"
            "    API->>Order: Create Order\n"
            "    Order-->>API: Order Created\n"
            "    API->>Inv: Confirm Reservation\n"
            "    API->>Cart: Clear Cart\n"
            "    API->>Email: Send Confirmation\n"
            "    API-->>UI: 201 Order Created\n"
            "    UI-->>U: Show Confirmation"
        ),
    },
    {
        "instruction": "Create a file upload with virus scan sequence diagram.",
        "input": "Flow: Select file -> Upload -> Scan -> Store -> Return URL",
        "output": (
            "sequenceDiagram\n"
            "    participant U as User\n"
            "    participant UI as Frontend\n"
            "    participant API as Backend\n"
            "    participant Scan as Virus Scanner\n"
            "    participant S3 as S3 Storage\n"
            "    participant DB as Database\n"
            "\n"
            "    U->>UI: Select File\n"
            "    UI->>UI: Validate Size/Type\n"
            "    UI->>API: POST /api/upload\n"
            "    API->>Scan: Scan File\n"
            "    Scan-->>API: Clean\n"
            "    API->>S3: Upload File\n"
            "    S3-->>API: File URL\n"
            "    API->>DB: Save Metadata\n"
            "    DB-->>API: Saved\n"
            "    API-->>UI: 200 OK + URL\n"
            "    UI-->>U: Upload Complete"
        ),
    },
    {
        "instruction": "Generate OAuth 2.0 authorization code flow diagram.",
        "input": "Flow: Login with Google -> Authorize -> Exchange code -> Get token -> Access resource",
        "output": (
            "sequenceDiagram\n"
            "    participant U as User\n"
            "    participant App as Application\n"
            "    participant Auth as Auth Server\n"
            "    participant API as Resource Server\n"
            "\n"
            "    U->>App: Click 'Login with Google'\n"
            "    App->>Auth: Redirect to Auth URL\n"
            "    U->>Auth: Enter Credentials\n"
            "    U->>Auth: Authorize App\n"
            "    Auth->>App: Redirect with Code\n"
            "    App->>Auth: POST /token (code)\n"
            "    Auth-->>App: Access Token + Refresh Token\n"
            "    App->>API: GET /api/user (+ token)\n"
            "    API-->>App: User Data\n"
            "    App-->>U: Login Success"
        ),
    },
]

# =============================================================================
# CODE GENERATION EXAMPLES (MongoDB + .NET + Angular focus - 30+ examples)
# =============================================================================

CODE_EXAMPLES = [
    {
        "instruction": "Generate a .NET controller with MongoDB integration using IMongoDBSettings.",
        "input": "Controller: ProductsController with CRUD operations, using MongoDB",
        "output": (
            "using Microsoft.AspNetCore.Mvc;\n"
            "using MongoDB.Driver;\n"
            "using MyApp.Settings;\n"
            "using MyApp.DTOs;\n"
            "\n"
            "namespace MyApp.Controllers\n"
            "{\n"
            "    [ApiController]\n"
            "    [Route(\"api/[controller]\")]\n"
            "    public class ProductsController : Controller\n"
            "    {\n"
            "        private readonly IMongoCollection<ProductDto> _products;\n"
            "\n"
            "        public ProductsController(IMongoDBSettings settings)\n"
            "        {\n"
            "            var client = new MongoClient(settings.ConnectionString);\n"
            "            var database = client.GetDatabase(settings.DatabaseName);\n"
            "            _products = database.GetCollection<ProductDto>(\"products\");\n"
            "        }\n"
            "\n"
            "        [HttpGet]\n"
            "        public ActionResult<List<ProductDto>> Get() =>\n"
            "            _products.Find(product => true).ToList();\n"
            "\n"
            "        [HttpGet(\"{id}\")]\n"
            "        public ActionResult<ProductDto> Get(string id)\n"
            "        {\n"
            "            var product = _products.Find(p => p.Id == id).FirstOrDefault();\n"
            "            if (product == null)\n"
            "                return NotFound();\n"
            "            return product;\n"
            "        }\n"
            "\n"
            "        [HttpPost]\n"
            "        public ActionResult<ProductDto> Create(ProductDto product)\n"
            "        {\n"
            "            _products.InsertOne(product);\n"
            "            return CreatedAtAction(nameof(Get), new { id = product.Id }, product);\n"
            "        }\n"
            "\n"
            "        [HttpPut(\"{id}\")]\n"
            "        public IActionResult Update(string id, ProductDto productIn)\n"
            "        {\n"
            "            var result = _products.ReplaceOne(p => p.Id == id, productIn);\n"
            "            if (result.ModifiedCount == 0)\n"
            "                return NotFound();\n"
            "            return NoContent();\n"
            "        }\n"
            "\n"
            "        [HttpDelete(\"{id}\")]\n"
            "        public IActionResult Delete(string id)\n"
            "        {\n"
            "            var result = _products.DeleteOne(p => p.Id == id);\n"
            "            if (result.DeletedCount == 0)\n"
            "                return NotFound();\n"
            "            return NoContent();\n"
            "        }\n"
            "    }\n"
            "}"
        ),
    },
    {
        "instruction": "Create a DTO class following XxxDto naming convention.",
        "input": "DTO: User with Id, Email, Name, CreatedAt properties",
        "output": (
            "using MongoDB.Bson;\n"
            "using MongoDB.Bson.Serialization.Attributes;\n"
            "using System;\n"
            "\n"
            "namespace MyApp.DTOs\n"
            "{\n"
            "    public class UserDto\n"
            "    {\n"
            "        [BsonId]\n"
            "        [BsonRepresentation(BsonType.ObjectId)]\n"
            "        public string Id { get; set; }\n"
            "\n"
            "        [BsonElement(\"email\")]\n"
            "        public string Email { get; set; }\n"
            "\n"
            "        [BsonElement(\"name\")]\n"
            "        public string Name { get; set; }\n"
            "\n"
            "        [BsonElement(\"createdAt\")]\n"
            "        public DateTime CreatedAt { get; set; }\n"
            "    }\n"
            "}"
        ),
    },
    {
        "instruction": "Generate an Angular service with HttpClient for API calls.",
        "input": "Service: UserService with methods to get, create, update, delete users",
        "output": (
            "import { Injectable } from '@angular/core';\n"
            "import { HttpClient } from '@angular/common/http';\n"
            "import { Observable } from 'rxjs';\n"
            "import { User } from '../models/user';\n"
            "\n"
            "@Injectable({\n"
            "  providedIn: 'root'\n"
            "})\n"
            "export class UserService {\n"
            "  private apiUrl = '/api/users';\n"
            "\n"
            "  constructor(private http: HttpClient) {}\n"
            "\n"
            "  getUsers(): Observable<User[]> {\n"
            "    return this.http.get<User[]>(this.apiUrl);\n"
            "  }\n"
            "\n"
            "  getUserById(id: string): Observable<User> {\n"
            "    return this.http.get<User>(`${this.apiUrl}/${id}`);\n"
            "  }\n"
            "\n"
            "  createUser(user: User): Observable<User> {\n"
            "    return this.http.post<User>(this.apiUrl, user);\n"
            "  }\n"
            "\n"
            "  updateUser(id: string, user: User): Observable<void> {\n"
            "    return this.http.put<void>(`${this.apiUrl}/${id}`, user);\n"
            "  }\n"
            "\n"
            "  deleteUser(id: string): Observable<void> {\n"
            "    return this.http.delete<void>(`${this.apiUrl}/${id}`);\n"
            "  }\n"
            "}"
        ),
    },
]

# Combine all examples
ALL_EXPANDED_EXAMPLES = ERD_EXAMPLES + ARCHITECTURE_EXAMPLES + SEQUENCE_EXAMPLES + CODE_EXAMPLES

print(f"Total expanded examples: {len(ALL_EXPANDED_EXAMPLES)}")
