"""
Export Manager Component
Export to PDF, PowerPoint, Markdown, Confluence
"""

import streamlit as st
from pathlib import Path
from typing import Dict, List
import base64
from datetime import datetime


class ExportManager:
    """Handle exports to various formats"""
    
    def __init__(self, outputs_dir: str = "outputs"):
        self.outputs_dir = Path(outputs_dir)
    
    def export_to_markdown(self, artifacts: Dict[str, str]) -> str:
        """Export all artifacts to combined Markdown"""
        
        md_content = f"""# Project Architecture Documentation
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

"""
        
        # Add each artifact as a section
        sections = {
            "design.md": "## Design Document",
            "architecture.md": "## Architecture",
            "api.md": "## API Documentation",
            "jira_tasks.md": "## Tasks & Stories",
            "workflows.md": "## Workflows"
        }
        
        for filename, title in sections.items():
            if filename in artifacts:
                md_content += f"\n{title}\n\n{artifacts[filename]}\n\n---\n\n"
        
        # Add diagrams
        if "diagrams" in artifacts:
            md_content += "\n## Diagrams\n\n"
            for diagram_name, diagram_code in artifacts["diagrams"].items():
                md_content += f"\n### {diagram_name}\n\n```mermaid\n{diagram_code}\n```\n\n"
        
        return md_content
    
    def export_to_html(self, artifacts: Dict[str, str]) -> str:
        """Export all artifacts to HTML"""
        
        html_template = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project Architecture Documentation</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 20px;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            overflow: hidden;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            text-align: center;
        }}
        .header h1 {{
            font-size: 2.5em;
            margin-bottom: 10px;
        }}
        .header p {{
            opacity: 0.9;
        }}
        .content {{
            padding: 40px;
        }}
        .section {{
            margin-bottom: 50px;
        }}
        .section h2 {{
            color: #667eea;
            border-bottom: 3px solid #667eea;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }}
        .section h3 {{
            color: #764ba2;
            margin-top: 20px;
            margin-bottom: 10px;
        }}
        pre {{
            background: #f5f5f5;
            padding: 15px;
            border-radius: 8px;
            overflow-x: auto;
            border-left: 4px solid #667eea;
        }}
        code {{
            font-family: 'Courier New', monospace;
            background: #f5f5f5;
            padding: 2px 6px;
            border-radius: 4px;
        }}
        .diagram {{
            background: #f9f9f9;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background: #667eea;
            color: white;
        }}
        .footer {{
            background: #f5f5f5;
            padding: 20px;
            text-align: center;
            color: #666;
        }}
    </style>
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <script>mermaid.initialize({{ startOnLoad: true, theme: 'default' }});</script>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📐 Project Architecture Documentation</h1>
            <p>Generated: {date}</p>
        </div>
        <div class="content">
            {content}
        </div>
        <div class="footer">
            <p>Generated by Architect.AI v2.0 | © {year}</p>
        </div>
    </div>
</body>
</html>
"""
        
        # Build content sections
        content_html = ""
        
        sections = {
            "design.md": "Design Document",
            "architecture.md": "Architecture",
            "api.md": "API Documentation",
            "jira_tasks.md": "Tasks & Stories",
            "workflows.md": "Workflows"
        }
        
        for filename, title in sections.items():
            if filename in artifacts:
                # Convert markdown to HTML (simple version)
                html_content = self._markdown_to_html(artifacts[filename])
                content_html += f'<div class="section"><h2>{title}</h2>{html_content}</div>'
        
        # Add diagrams
        if "diagrams" in artifacts:
            content_html += '<div class="section"><h2>Diagrams</h2>'
            for diagram_name, diagram_code in artifacts["diagrams"].items():
                content_html += f'''
                <div class="diagram">
                    <h3>{diagram_name}</h3>
                    <div class="mermaid">
                    {diagram_code}
                    </div>
                </div>
                '''
            content_html += '</div>'
        
        return html_template.format(
            date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            year=datetime.now().year,
            content=content_html
        )
    
    def _markdown_to_html(self, markdown: str) -> str:
        """Simple markdown to HTML conversion"""
        import re
        
        html = markdown
        
        # Headers
        html = re.sub(r'^### (.*?)$', r'<h3>\1</h3>', html, flags=re.MULTILINE)
        html = re.sub(r'^## (.*?)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
        html = re.sub(r'^# (.*?)$', r'<h1>\1</h1>', html, flags=re.MULTILINE)
        
        # Lists
        html = re.sub(r'^\- (.*?)$', r'<li>\1</li>', html, flags=re.MULTILINE)
        html = re.sub(r'(<li>.*?</li>\n?)+', r'<ul>\g<0></ul>', html, flags=re.DOTALL)
        
        # Code blocks
        html = re.sub(r'```(.*?)```', r'<pre><code>\1</code></pre>', html, flags=re.DOTALL)
        
        # Inline code
        html = re.sub(r'`(.*?)`', r'<code>\1</code>', html)
        
        # Bold
        html = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', html)
        
        # Italic
        html = re.sub(r'\*(.*?)\*', r'<em>\1</em>', html)
        
        # Paragraphs
        html = re.sub(r'\n\n', r'</p><p>', html)
        html = f'<p>{html}</p>'
        
        return html
    
    def export_to_powerpoint_script(self, artifacts: Dict[str, str]) -> str:
        """Generate Python script to create PowerPoint"""
        
        script = '''
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from datetime import datetime

# Create presentation
prs = Presentation()
prs.slide_width = Inches(16)
prs.slide_height = Inches(9)

# Title slide
title_slide = prs.slides.add_slide(prs.slide_layouts[0])
title = title_slide.shapes.title
subtitle = title_slide.placeholders[1]
title.text = "Project Architecture"
subtitle.text = f"Generated: {datetime.now().strftime('%Y-%m-%d')}"

'''
        
        # Add slides for each artifact
        sections = {
            "design.md": "Design Document",
            "architecture.md": "Architecture Overview",
            "api.md": "API Documentation",
            "jira_tasks.md": "Implementation Tasks"
        }
        
        for filename, title in sections.items():
            if filename in artifacts:
                script += f'''
# {title} slide
slide = prs.slides.add_slide(prs.slide_layouts[1])
title = slide.shapes.title
title.text = "{title}"
body = slide.placeholders[1]
tf = body.text_frame
tf.text = """
{artifacts[filename][:500]}...
"""

'''
        
        script += '''
# Save presentation
prs.save('architecture_presentation.pptx')
print("✅ PowerPoint created: architecture_presentation.pptx")
'''
        
        return script
    
    def export_to_confluence(self, artifacts: Dict[str, str]) -> str:
        """Generate Confluence Wiki markup"""
        
        confluence = f"""h1. Project Architecture Documentation
{{info}}Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}{{info}}

----

"""
        
        sections = {
            "design.md": "Design Document",
            "architecture.md": "Architecture",
            "api.md": "API Documentation",
            "jira_tasks.md": "Tasks"
        }
        
        for filename, title in sections.items():
            if filename in artifacts:
                # Convert to Confluence markup
                content = artifacts[filename]
                content = content.replace('##', 'h2.')
                content = content.replace('###', 'h3.')
                content = content.replace('```', '{code}')
                
                confluence += f"\nh2. {title}\n\n{content}\n\n----\n\n"
        
        # Add diagrams
        if "diagrams" in artifacts:
            confluence += "\nh2. Diagrams\n\n"
            for diagram_name, diagram_code in artifacts["diagrams"].items():
                confluence += f"\nh3. {diagram_name}\n\n{{code:mermaid}}\n{diagram_code}\n{{code}}\n\n"
        
        return confluence


def render_export_manager():
    """Render export UI"""
    
    st.markdown("### 📤 Export Documentation")
    
    manager = ExportManager()
    
    # Collect all artifacts
    artifacts = {}
    diagrams = {}
    
    # Load documentation
    docs_dir = manager.outputs_dir / "documentation"
    if docs_dir.exists():
        for doc_file in docs_dir.glob("*.md"):
            artifacts[doc_file.name] = doc_file.read_text(encoding='utf-8')
    
    # Load diagrams
    viz_dir = manager.outputs_dir / "visualizations"
    if viz_dir.exists():
        for diagram_file in viz_dir.glob("*.mmd"):
            diagrams[diagram_file.stem] = diagram_file.read_text(encoding='utf-8')
    
    if diagrams:
        artifacts["diagrams"] = diagrams
    
    if not artifacts:
        st.info("No artifacts found. Generate some documentation first!")
        return
    
    # Export format selection
    export_format = st.selectbox(
        "Export Format",
        ["Markdown (Combined)", "HTML (Interactive)", "PowerPoint Script", "Confluence Wiki"],
        key="export_format"
    )
    
    # Preview
    with st.expander("📋 Preview Export Content"):
        st.json({k: f"{len(v)} chars" for k, v in artifacts.items() if k != "diagrams"})
        if "diagrams" in artifacts:
            st.write(f"📊 {len(diagrams)} diagrams")
    
    # Export button
    if st.button("📤 Export Now", use_container_width=True, type="primary"):
        with st.spinner(f"Generating {export_format}..."):
            
            if export_format == "Markdown (Combined)":
                content = manager.export_to_markdown(artifacts)
                st.download_button(
                    "💾 Download Markdown",
                    content,
                    "architecture_documentation.md",
                    "text/markdown",
                    use_container_width=True
                )
                st.success("✅ Markdown export ready!")
            
            elif export_format == "HTML (Interactive)":
                content = manager.export_to_html(artifacts)
                st.download_button(
                    "💾 Download HTML",
                    content,
                    "architecture_documentation.html",
                    "text/html",
                    use_container_width=True
                )
                st.success("✅ HTML export ready! Open in browser to view.")
            
            elif export_format == "PowerPoint Script":
                script = manager.export_to_powerpoint_script(artifacts)
                st.download_button(
                    "💾 Download Python Script",
                    script,
                    "create_powerpoint.py",
                    "text/x-python",
                    use_container_width=True
                )
                st.info("""
📝 **Instructions:**
1. Install: `pip install python-pptx`
2. Run: `python create_powerpoint.py`
3. Open: `architecture_presentation.pptx`
                """)
            
            elif export_format == "Confluence Wiki":
                content = manager.export_to_confluence(artifacts)
                st.download_button(
                    "💾 Download Confluence Markup",
                    content,
                    "confluence_export.txt",
                    "text/plain",
                    use_container_width=True
                )
                st.info("Copy content and paste into Confluence page editor")
    
    # Bulk download
    st.divider()
    st.markdown("#### 📦 Bulk Download")
    
    if st.button("📦 Download All Files (ZIP)", use_container_width=True):
        st.info("ZIP export coming soon! For now, download individual formats above.")

