"""
Mermaid HTML Renderer with Gemini Comparison
Generates both Mermaid diagrams and HTML visualizations for comparison
"""

import streamlit as st
import asyncio
from typing import Dict, List, Tuple, Optional, TYPE_CHECKING
from dataclasses import dataclass
from pathlib import Path
import json
import base64
from datetime import datetime
if TYPE_CHECKING:
    from agents.universal_agent import UniversalArchitectAgent


@dataclass
class DiagramComparison:
    """Represents a comparison between Mermaid and HTML diagrams"""
    mermaid_content: str
    html_content: str
    mermaid_rendered: bool
    html_rendered: bool
    comparison_notes: str
    generation_time: float


class MermaidHTMLRenderer:
    """Renders Mermaid diagrams as HTML and generates visual comparisons"""
    
    def __init__(self):
        self.mermaid_js_url = "https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js"
        self.comparison_history = []
        # Latest pre-tokenization RAG debug entries (for transparency)
        self.last_rag_debug: List[Dict[str, str]] = []
    
    def render_mermaid_as_html(self, mermaid_content: str, diagram_id: str = None) -> str:
        """Render Mermaid diagram as HTML with embedded Mermaid.js"""
        
        if not diagram_id:
            diagram_id = f"diagram_{int(datetime.now().timestamp())}"
        
        html_template = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Mermaid Diagram</title>
            <script src="{self.mermaid_js_url}"></script>
            <style>
                body {{
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                    margin: 0;
                    padding: 20px;
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    min-height: 100vh;
                }}
                .container {{
                    max-width: 1200px;
                    margin: 0 auto;
                    background: white;
                    border-radius: 12px;
                    box-shadow: 0 20px 40px rgba(0,0,0,0.1);
                    overflow: hidden;
                }}
                .header {{
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    color: white;
                    padding: 20px;
                    text-align: center;
                }}
                .header h1 {{
                    margin: 0;
                    font-size: 24px;
                    font-weight: 300;
                }}
                .diagram-container {{
                    padding: 30px;
                    text-align: center;
                }}
                .mermaid {{
                    background: #f8f9fa;
                    border-radius: 8px;
                    padding: 20px;
                    margin: 20px 0;
                }}
                .info {{
                    background: #e3f2fd;
                    border-left: 4px solid #2196f3;
                    padding: 15px;
                    margin: 20px 0;
                    border-radius: 4px;
                }}
                .info h3 {{
                    margin: 0 0 10px 0;
                    color: #1976d2;
                }}
                .info p {{
                    margin: 0;
                    color: #424242;
                }}
                .footer {{
                    background: #f5f5f5;
                    padding: 15px;
                    text-align: center;
                    color: #666;
                    font-size: 12px;
                }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>🎨 Mermaid Diagram Visualization</h1>
                </div>
                
                <div class="diagram-container">
                    <div class="info">
                        <h3>📊 Interactive Diagram</h3>
                        <p>This diagram is rendered using Mermaid.js and is fully interactive. You can zoom, pan, and interact with the elements.</p>
                    </div>
                    
                    <div class="mermaid" id="{diagram_id}">
                        {mermaid_content}
                    </div>
                    
                    <div class="info">
                        <h3>🔧 Technical Details</h3>
                        <p><strong>Diagram ID:</strong> {diagram_id}</p>
                        <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                        <p><strong>Mermaid Version:</strong> 10.6.1</p>
                    </div>
                </div>
                
                <div class="footer">
                    <p>Generated by Architect.AI - Mermaid HTML Renderer</p>
                </div>
            </div>
            
            <script>
                mermaid.initialize({{
                    startOnLoad: true,
                    theme: 'default',
                    themeVariables: {{
                        primaryColor: '#667eea',
                        primaryTextColor: '#333',
                        primaryBorderColor: '#764ba2',
                        lineColor: '#666',
                        secondaryColor: '#f8f9fa',
                        tertiaryColor: '#e3f2fd'
                    }},
                    flowchart: {{
                        useMaxWidth: true,
                        htmlLabels: true
                    }},
                    sequence: {{
                        useMaxWidth: true,
                        wrap: true
                    }},
                    gantt: {{
                        useMaxWidth: true
                    }}
                }});
                
                // Add interactivity
                document.addEventListener('DOMContentLoaded', function() {{
                    const diagram = document.getElementById('{diagram_id}');
                    if (diagram) {{
                        diagram.style.cursor = 'grab';
                        diagram.addEventListener('click', function(e) {{
                            console.log('Diagram clicked:', e.target);
                        }});
                    }}
                }});
            </script>
        </body>
        </html>
        """
        
        return html_template
    
    async def generate_html_visualization_with_gemini(
        self,
        mermaid_content: str,
        meeting_notes: str = "",
        diagram_type: str = "flowchart",
        rag_context: str = "",
        agent: Optional['UniversalArchitectAgent'] = None,
    ) -> str:
        """Generate HTML visualization using Gemini AI with RAG context"""
        
        agent = agent or self._get_runtime_agent()
        if agent is None:
            print("[WARN] No AI agent available for HTML visualization; using static layout")
            return self._create_fallback_html(mermaid_content, meeting_notes, diagram_type)
        if meeting_notes:
            agent.meeting_notes = meeting_notes
        
        context_text = ""

        if rag_context:
            try:
                from components.enhanced_rag import ContextAssembly  # type: ignore
                if isinstance(rag_context, ContextAssembly):
                    context_text = rag_context.context_text or ""
                elif isinstance(rag_context, dict) and 'context_text' in rag_context:
                    context_text = rag_context.get('context_text', '')
                else:
                    context_text = str(rag_context)
            except Exception:
                context_text = str(rag_context)

        if not context_text:
            enhanced = getattr(agent, 'enhanced_rag_context', None)
            if enhanced is not None:
                context_text = getattr(enhanced, 'context_text', '') or ""
        if not context_text:
            context_text = getattr(agent, 'rag_context', '') or ""

        if not context_text and meeting_notes:
            try:
                from rag.retrieve import vector_search, bm25_search, merge_rerank
                from rag.context_optimizer import optimize_context
                
                if agent.collection:
                    vector_results = vector_search(meeting_notes, agent.collection, top_k=10)
                    bm25_results = bm25_search(meeting_notes, agent.cfg, top_k=10)
                    merged = merge_rerank(vector_results, bm25_results, top_k=10)

                    self.last_rag_debug = []
                    context_text = optimize_context(merged, max_tokens=2000)
            except Exception as e:
                print(f"[WARN] Could not retrieve supplemental RAG context for HTML: {e}")
        
        prompt = f"""
        Create a beautiful, interactive HTML visualization based on the following information.
        
        YOU DECIDE: Analyze the context and meeting notes below, then create the BEST type of diagram that represents this information.
        You can create:
        - An ERD (Entity Relationship Diagram) for database models
        - A System Architecture diagram for services/components
        - A Flowchart for processes and workflows
        - A Sequence diagram for API interactions
        - A Component diagram for frontend structure
        - Or ANY other diagram type that best fits the information
        
        REFERENCE MERMAID STRUCTURE (optional - you can improve or change the diagram type):
        ```
        {mermaid_content if mermaid_content else "No Mermaid diagram provided - create from scratch"}
        ```
        
        FEATURE REQUIREMENTS FROM MEETING NOTES:
        {meeting_notes if meeting_notes else "No specific meeting notes - analyze the repository context"}
        
        ACTUAL REPOSITORY CODE & STRUCTURE (Use this as the SOURCE OF TRUTH):
        {context_text if context_text else "No repository context available"}
        
        YOUR TASK:
        1. Analyze the repository context and meeting notes
        2. Decide which diagram type best represents this information
        3. Create a modern, interactive HTML visualization with:
           - Professional color scheme (blues, grays, whites with gradients)
           - Smooth CSS animations and hover effects
           - Mobile-responsive design
           - Clear header with title
           - Interactive tooltips showing details from the actual codebase
           - Proper spacing and visual hierarchy
           - Footer with generation metadata
        4. **CRITICAL**: Use ACTUAL names from the repository context (real table names, API endpoints, component names, etc.)
        5. Make it accurate and technically correct based on the repository code
        
        OUTPUT: Complete, self-contained HTML page with embedded CSS and JavaScript. No external dependencies or libraries.
        """
        
        try:
            html_content = await agent._call_ai(
                prompt, 
                "You are an expert web developer who creates accurate, context-aware HTML visualizations. Use the repository context to ensure technical accuracy."
            )
            
            # Check if we got valid content
            if not html_content or len(html_content.strip()) < 100:
                print("[WARN] Gemini returned insufficient content for HTML visualization, using static fallback")
                return self._create_fallback_html(mermaid_content, meeting_notes, diagram_type)
            
            # Clean up the HTML content
            html_content = self._clean_html_content(html_content)
            
            # Validate HTML has proper structure
            if '<html' not in html_content.lower() or '</html>' not in html_content.lower():
                print("[WARN] Generated HTML lacks proper structure, using static fallback")
                return self._create_fallback_html(mermaid_content, meeting_notes, diagram_type)
            
            print(f"[OK] Generated custom HTML visualization with Gemini")
            return html_content
            
        except Exception as e:
            print(f"[WARN] Gemini HTML generation failed ({str(e)}), using static fallback")
            return self._create_fallback_html(mermaid_content, meeting_notes, diagram_type)
    
    def _clean_html_content(self, html_content: str) -> str:
        """Clean and validate HTML content"""
        
        # Remove any markdown code blocks
        if html_content.startswith('```html'):
            html_content = html_content[7:]
        if html_content.endswith('```'):
            html_content = html_content[:-3]
        
        # Ensure proper HTML structure
        if not html_content.strip().startswith('<!DOCTYPE html>'):
            html_content = f"<!DOCTYPE html>\n{html_content}"
        
        return html_content.strip()
    
    def _create_fallback_html(self, mermaid_content: str, meeting_notes: str, diagram_type: str) -> str:
        """Create a static HTML visualization without relying on Mermaid."""

        title = diagram_type.replace("_", " ").title() if diagram_type else "Diagram"
        summary_section = ""
        if mermaid_content:
            preview = mermaid_content[:400].replace("`", "&#96;")
            summary_section = f"<pre class=\"preview\">{preview}{'…' if len(mermaid_content) > 400 else ''}</pre>"
        meeting_section = ""
        if meeting_notes:
            meeting_preview = "\n".join(meeting_notes.strip().splitlines()[:5])
            meeting_section = (
                "<div class=\"panel\"><h3>Meeting Context</h3><p>"
                f"{meeting_preview}</p></div>"
            )

        return f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} Visualization</title>
    <style>
        body {{
            font-family: 'Segoe UI', sans-serif;
            margin: 0;
            padding: 0;
            background: linear-gradient(135deg, #111827, #1f2937);
            color: #e5e7eb;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            padding: 32px;
        }}
        .card {{
            background: rgba(30, 41, 59, 0.9);
            border-radius: 16px;
            padding: 32px;
            box-shadow: 0 25px 50px -12px rgba(15, 23, 42, 0.6);
        }}
        h1 {{
            margin-top: 0;
            font-size: 32px;
            letter-spacing: 0.02em;
        }}
        .grid {{
            display: grid;
            gap: 16px;
            grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
            margin-top: 24px;
        }}
        .panel {{
            background: rgba(15, 23, 42, 0.65);
            border-radius: 12px;
            padding: 20px;
        }}
        .badge {{
            display: inline-block;
            padding: 6px 12px;
            border-radius: 999px;
            background: rgba(59, 130, 246, 0.15);
            color: #93c5fd;
            font-size: 12px;
            letter-spacing: 0.06em;
        }}
        .preview {{
            background: rgba(15, 23, 42, 0.8);
            padding: 16px;
            border-radius: 12px;
            overflow-x: auto;
            white-space: pre-wrap;
            color: #f9fafb;
            font-size: 13px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <span class="badge">Fallback Visualization</span>
            <h1>{title}</h1>
            <p>This static layout summarises the latest diagram content while the live HTML renderer is unavailable.</p>
            {summary_section}
            <div class="grid">
                <div class="panel">
                    <h3>What's Next?</h3>
                    <p>Regenerate the HTML visualization once your AI provider is reachable. The dataset builder will still incorporate this diagram text.</p>
                </div>
                <div class="panel">
                    <h3>Tip</h3>
                    <p>Use the interactive editor to tweak the Mermaid definition, then choose “Generate HTML” to request a fresh LLM-rendered experience.</p>
                </div>
                {meeting_section}
            </div>
        </div>
    </div>
</body>
</html>
"""

    def _get_runtime_agent(self) -> Optional['UniversalArchitectAgent']:
        try:
            from app.app_v2 import resolve_provider_runtime, get_or_create_agent

            runtime_context, error = resolve_provider_runtime()
            if error or not runtime_context:
                print(f"[WARN] Runtime agent unavailable: {error}")
                return None
            return get_or_create_agent(runtime_context['config'])
        except Exception as exc:
            print(f"[WARN] Failed to reuse runtime agent: {exc}")
            return None
    
    def create_comparison(self, mermaid_content: str, html_content: str, 
                         meeting_notes: str = "") -> DiagramComparison:
        """Create a comparison between Mermaid and HTML versions"""
        
        start_time = datetime.now()
        
        # Test if Mermaid renders properly
        mermaid_rendered = self._test_mermaid_rendering(mermaid_content)
        
        # Test if HTML is valid
        html_rendered = self._test_html_rendering(html_content)
        
        # Generate comparison notes
        comparison_notes = self._generate_comparison_notes(
            mermaid_content, html_content, mermaid_rendered, html_rendered
        )
        
        end_time = datetime.now()
        generation_time = (end_time - start_time).total_seconds()
        
        comparison = DiagramComparison(
            mermaid_content=mermaid_content,
            html_content=html_content,
            mermaid_rendered=mermaid_rendered,
            html_rendered=html_rendered,
            comparison_notes=comparison_notes,
            generation_time=generation_time
        )
        
        self.comparison_history.append(comparison)
        return comparison
    
    def _test_mermaid_rendering(self, mermaid_content: str) -> bool:
        """Test if Mermaid content can be rendered"""
        try:
            # Basic syntax validation
            if not mermaid_content.strip():
                return False
            
            # Check for basic Mermaid structure
            valid_starters = ['flowchart', 'graph', 'sequenceDiagram', 'classDiagram', 
                            'stateDiagram', 'erDiagram', 'gantt', 'pie', 'journey']
            
            first_line = mermaid_content.split('\n')[0].strip().lower()
            return any(first_line.startswith(starter) for starter in valid_starters)
            
        except Exception:
            return False
    
    def _test_html_rendering(self, html_content: str) -> bool:
        """Test if HTML content is valid"""
        try:
            # Basic HTML validation
            if not html_content.strip():
                return False
            
            # Check for basic HTML structure
            return ('<!DOCTYPE html>' in html_content or '<html' in html_content) and '</html>' in html_content
            
        except Exception:
            return False
    
    def _generate_comparison_notes(self, mermaid_content: str, html_content: str, 
                                 mermaid_rendered: bool, html_rendered: bool) -> str:
        """Generate comparison notes between Mermaid and HTML versions"""
        
        notes = []
        
        if mermaid_rendered and html_rendered:
            notes.append("✅ Both Mermaid and HTML versions are valid and renderable")
        elif mermaid_rendered and not html_rendered:
            notes.append("✅ Mermaid version is valid, ⚠️ HTML version has issues")
        elif not mermaid_rendered and html_rendered:
            notes.append("⚠️ Mermaid version has issues, ✅ HTML version is valid")
        else:
            notes.append("❌ Both versions have rendering issues")
        
        # Compare content complexity
        mermaid_lines = len(mermaid_content.split('\n'))
        html_lines = len(html_content.split('\n'))
        
        if html_lines > mermaid_lines * 2:
            notes.append("📊 HTML version is significantly more detailed than Mermaid")
        elif html_lines > mermaid_lines:
            notes.append("📊 HTML version is more detailed than Mermaid")
        else:
            notes.append("📊 Both versions have similar complexity")
        
        # Check for interactive elements
        if 'onclick' in html_content or 'addEventListener' in html_content:
            notes.append("🎯 HTML version includes interactive elements")
        
        if 'hover' in html_content or 'transition' in html_content:
            notes.append("🎨 HTML version includes animations and effects")
        
        return " | ".join(notes)


# Global instance
mermaid_html_renderer = MermaidHTMLRenderer()


def render_mermaid_html_comparison():
    """Streamlit UI for Mermaid HTML comparison"""
    
    st.subheader("🎨 Mermaid vs HTML Diagram Comparison")
    
    # Input section
    col1, col2 = st.columns(2)
    
    with col1:
        st.write("**📝 Meeting Notes Context:**")
        meeting_notes = st.text_area(
            "Meeting Notes:",
            height=100,
            placeholder="Enter meeting notes or requirements for context...",
            key="meeting_notes_comparison"
        )
    
    with col2:
        st.write("**🔧 Diagram Type:**")
        diagram_type = st.selectbox(
            "Select Diagram Type:",
            ["flowchart", "sequenceDiagram", "classDiagram", "stateDiagram", "erDiagram", "gantt", "pie", "journey"],
            key="diagram_type_comparison"
        )
    
    # Mermaid input
    st.write("**📊 Mermaid Diagram:**")
    mermaid_content = st.text_area(
        "Enter Mermaid Diagram:",
        height=200,
        placeholder="flowchart TD\n    A[Start] --> B[Process]\n    B --> C[End]",
        key="mermaid_input_comparison"
    )
    
    # Generate buttons
    col1, col2 = st.columns(2)
    
    with col1:
        if st.button("🎨 Generate HTML with Gemini", type="primary"):
            if not mermaid_content.strip():
                st.warning("Please enter a Mermaid diagram")
                return
            
            with st.spinner("Generating HTML visualization with Gemini..."):
                try:
                    html_content = asyncio.run(
                        mermaid_html_renderer.generate_html_visualization_with_gemini(
                            mermaid_content, meeting_notes, diagram_type
                        )
                    )
                    
                    # Create comparison
                    comparison = mermaid_html_renderer.create_comparison(
                        mermaid_content, html_content, meeting_notes
                    )
                    
                    st.session_state.comparison_result = comparison
                    st.success("✅ HTML visualization generated!")
                    
                except Exception as e:
                    st.error(f"❌ Error generating HTML: {str(e)}")
    
    with col2:
        if st.button("🔄 Render with Mermaid.js (no AI)"):
            if not mermaid_content.strip():
                st.warning("Please enter a Mermaid diagram")
                return
            
            try:
                html_content = mermaid_html_renderer.render_mermaid_as_html(mermaid_content)
                
                # Create comparison
                comparison = mermaid_html_renderer.create_comparison(
                    mermaid_content, html_content, meeting_notes
                )
                
                st.session_state.comparison_result = comparison
                st.success("✅ Mermaid rendered as HTML!")
                
            except Exception as e:
                st.error(f"❌ Error rendering Mermaid: {str(e)}")

    # Optional RAG debug viewer
    if 'rag_debug' in st.session_state:
        with st.expander("🐞 View RAG Debug (pre-tokenization)", expanded=False):
            entries = st.session_state.get('rag_debug') or []
            if not entries:
                st.caption("No RAG results captured for this request.")
            else:
                for i, entry in enumerate(entries, start=1):
                    st.markdown(f"**{i}. {entry.get('path','')} (score {entry.get('score','')})**")
                    st.code(entry.get('content_preview',''), language='text')
    
    # Display results
    if 'comparison_result' in st.session_state:
        comparison = st.session_state.comparison_result
        
        st.divider()
        
        # Comparison summary
        st.write("**📊 Comparison Summary:**")
        col1, col2, col3 = st.columns(3)
        
        with col1:
            status = "✅ Valid" if comparison.mermaid_rendered else "❌ Invalid"
            st.metric("Mermaid Status", status)
        
        with col2:
            status = "✅ Valid" if comparison.html_rendered else "❌ Invalid"
            st.metric("HTML Status", status)
        
        with col3:
            st.metric("Generation Time", f"{comparison.generation_time:.2f}s")
        
        st.info(f"**Notes:** {comparison.comparison_notes}")
        
        # Display both versions
        tab1, tab2, tab3 = st.tabs(["🎨 HTML Visualization", "📊 Mermaid Source", "🔍 Side by Side"])
        
        with tab1:
            st.write("**HTML Visualization:**")
            st.components.v1.html(comparison.html_content, height=600, scrolling=True)
        
        with tab2:
            st.write("**Mermaid Source:**")
            st.code(comparison.mermaid_content, language="mermaid")
        
        with tab3:
            col1, col2 = st.columns(2)
            
            with col1:
                st.write("**Mermaid:**")
                st.code(comparison.mermaid_content, language="mermaid")
            
            with col2:
                st.write("**HTML Preview:**")
                st.components.v1.html(comparison.html_content, height=400, scrolling=True)
        
        # Download options
        st.divider()
        st.write("**💾 Download Options:**")
        
        col1, col2, col3 = st.columns(3)
        
        with col1:
            if st.button("📄 Download HTML"):
                from pathlib import Path
                output_path = Path("outputs/visualizations/comparison.html")
                output_path.parent.mkdir(parents=True, exist_ok=True)
                output_path.write_text(comparison.html_content, encoding='utf-8')
                st.success(f"Saved to {output_path}")
        
        with col2:
            if st.button("📊 Download Mermaid"):
                from pathlib import Path
                output_path = Path("outputs/visualizations/comparison.mmd")
                output_path.parent.mkdir(parents=True, exist_ok=True)
                output_path.write_text(comparison.mermaid_content, encoding='utf-8')
                st.success(f"Saved to {output_path}")
        
        with col3:
            if st.button("📋 Download Both"):
                from pathlib import Path
                import zipfile
                
                output_dir = Path("outputs/visualizations")
                output_dir.mkdir(parents=True, exist_ok=True)
                
                with zipfile.ZipFile(output_dir / "comparison.zip", 'w') as zipf:
                    zipf.writestr("mermaid_diagram.mmd", comparison.mermaid_content)
                    zipf.writestr("html_visualization.html", comparison.html_content)
                    zipf.writestr("comparison_notes.txt", comparison.comparison_notes)
                
                st.success(f"Saved to {output_dir / 'comparison.zip'}")


def render_mermaid_html_comparison_tab():
    """Render the Mermaid HTML comparison tab"""
    render_mermaid_html_comparison()
