"""Mobile Development Training Examples (Kotlin, Swift, Flutter, React Native) - 20 examples"""

MOBILE_EXAMPLES = [
    # Kotlin/Android
    {
        "instruction": "Generate Kotlin ViewModel with StateFlow for Android.",
        "input": "ViewModel: User profile with loading, success, error states",
        "output": (
            "import androidx.lifecycle.ViewModel\n"
            "import androidx.lifecycle.viewModelScope\n"
            "import kotlinx.coroutines.flow.MutableStateFlow\n"
            "import kotlinx.coroutines.flow.StateFlow\n"
            "import kotlinx.coroutines.flow.asStateFlow\n"
            "import kotlinx.coroutines.launch\n"
            "\n"
            "data class UserProfile(\n"
            "    val id: Int,\n"
            "    val name: String,\n"
            "    val email: String,\n"
            "    val bio: String = \"\",\n"
            "    val avatarUrl: String? = null\n"
            ")\n"
            "\n"
            "sealed class ProfileUiState {\n"
            "    object Loading : ProfileUiState()\n"
            "    data class Success(val profile: UserProfile) : ProfileUiState()\n"
            "    data class Error(val message: String) : ProfileUiState()\n"
            "}\n"
            "\n"
            "class ProfileViewModel(\n"
            "    private val repository: UserRepository\n"
            ") : ViewModel() {\n"
            "\n"
            "    private val _uiState = MutableStateFlow<ProfileUiState>(ProfileUiState.Loading)\n"
            "    val uiState: StateFlow<ProfileUiState> = _uiState.asStateFlow()\n"
            "\n"
            "    init {\n"
            "        loadProfile()\n"
            "    }\n"
            "\n"
            "    fun loadProfile() {\n"
            "        viewModelScope.launch {\n"
            "            _uiState.value = ProfileUiState.Loading\n"
            "            try {\n"
            "                val profile = repository.getProfile()\n"
            "                _uiState.value = ProfileUiState.Success(profile)\n"
            "            } catch (e: Exception) {\n"
            "                _uiState.value = ProfileUiState.Error(\n"
            "                    e.message ?: \"Failed to load profile\"\n"
            "                )\n"
            "            }\n"
            "        }\n"
            "    }\n"
            "\n"
            "    fun updateProfile(profile: UserProfile) {\n"
            "        viewModelScope.launch {\n"
            "            try {\n"
            "                repository.updateProfile(profile)\n"
            "                _uiState.value = ProfileUiState.Success(profile)\n"
            "            } catch (e: Exception) {\n"
            "                _uiState.value = ProfileUiState.Error(\n"
            "                    e.message ?: \"Failed to update profile\"\n"
            "                )\n"
            "            }\n"
            "        }\n"
            "    }\n"
            "}"
        ),
    },
    
    # Swift/iOS
    {
        "instruction": "Generate SwiftUI view with ObservableObject and async data loading.",
        "input": "View: Product list with loading, error, and success states",
        "output": (
            "import SwiftUI\n"
            "\n"
            "struct Product: Identifiable, Codable {\n"
            "    let id: Int\n"
            "    let name: String\n"
            "    let price: Double\n"
            "    let imageUrl: String?\n"
            "}\n"
            "\n"
            "@MainActor\n"
            "class ProductListViewModel: ObservableObject {\n"
            "    @Published var products: [Product] = []\n"
            "    @Published var isLoading = false\n"
            "    @Published var errorMessage: String?\n"
            "    \n"
            "    private let service: ProductService\n"
            "    \n"
            "    init(service: ProductService = ProductService()) {\n"
            "        self.service = service\n"
            "    }\n"
            "    \n"
            "    func loadProducts() async {\n"
            "        isLoading = true\n"
            "        errorMessage = nil\n"
            "        \n"
            "        do {\n"
            "            products = try await service.fetchProducts()\n"
            "        } catch {\n"
            "            errorMessage = error.localizedDescription\n"
            "        }\n"
            "        \n"
            "        isLoading = false\n"
            "    }\n"
            "    \n"
            "    func refreshProducts() async {\n"
            "        await loadProducts()\n"
            "    }\n"
            "}\n"
            "\n"
            "struct ProductListView: View {\n"
            "    @StateObject private var viewModel = ProductListViewModel()\n"
            "    \n"
            "    var body: some View {\n"
            "        NavigationView {\n"
            "            Group {\n"
            "                if viewModel.isLoading {\n"
            "                    ProgressView(\"Loading products...\")\n"
            "                } else if let error = viewModel.errorMessage {\n"
            "                    VStack(spacing: 16) {\n"
            "                        Text(error)\n"
            "                            .foregroundColor(.red)\n"
            "                        Button(\"Retry\") {\n"
            "                            Task {\n"
            "                                await viewModel.loadProducts()\n"
            "                            }\n"
            "                        }\n"
            "                    }\n"
            "                } else {\n"
            "                    List(viewModel.products) { product in\n"
            "                        ProductRow(product: product)\n"
            "                    }\n"
            "                    .refreshable {\n"
            "                        await viewModel.refreshProducts()\n"
            "                    }\n"
            "                }\n"
            "            }\n"
            "            .navigationTitle(\"Products\")\n"
            "            .task {\n"
            "                await viewModel.loadProducts()\n"
            "            }\n"
            "        }\n"
            "    }\n"
            "}\n"
            "\n"
            "struct ProductRow: View {\n"
            "    let product: Product\n"
            "    \n"
            "    var body: some View {\n"
            "        HStack {\n"
            "            AsyncImage(url: URL(string: product.imageUrl ?? \"\")) { image in\n"
            "                image\n"
            "                    .resizable()\n"
            "                    .aspectRatio(contentMode: .fill)\n"
            "            } placeholder: {\n"
            "                Color.gray\n"
            "            }\n"
            "            .frame(width: 60, height: 60)\n"
            "            .cornerRadius(8)\n"
            "            \n"
            "            VStack(alignment: .leading, spacing: 4) {\n"
            "                Text(product.name)\n"
            "                    .font(.headline)\n"
            "                Text(\"$\\(product.price, specifier: \"%.2f\")\")\n"
            "                    .font(.subheadline)\n"
            "                    .foregroundColor(.secondary)\n"
            "            }\n"
            "        }\n"
            "        .padding(.vertical, 4)\n"
            "    }\n"
            "}"
        ),
    },
    
    # React Native
    {
        "instruction": "Generate React Native component with TypeScript and hooks.",
        "input": "Component: Search bar with debounced input and results",
        "output": (
            "import React, { useState, useEffect, useCallback } from 'react';\n"
            "import {\n"
            "  View,\n"
            "  TextInput,\n"
            "  FlatList,\n"
            "  Text,\n"
            "  ActivityIndicator,\n"
            "  StyleSheet,\n"
            "  TouchableOpacity,\n"
            "} from 'react-native';\n"
            "\n"
            "interface SearchResult {\n"
            "  id: string;\n"
            "  title: string;\n"
            "  description: string;\n"
            "}\n"
            "\n"
            "interface SearchBarProps {\n"
            "  onResultSelect: (result: SearchResult) => void;\n"
            "  placeholder?: string;\n"
            "}\n"
            "\n"
            "const SearchBar: React.FC<SearchBarProps> = ({\n"
            "  onResultSelect,\n"
            "  placeholder = 'Search...',\n"
            "}) => {\n"
            "  const [query, setQuery] = useState('');\n"
            "  const [results, setResults] = useState<SearchResult[]>([]);\n"
            "  const [loading, setLoading] = useState(false);\n"
            "  const [error, setError] = useState<string | null>(null);\n"
            "\n"
            "  // Debounced search\n"
            "  useEffect(() => {\n"
            "    if (!query.trim()) {\n"
            "      setResults([]);\n"
            "      return;\n"
            "    }\n"
            "\n"
            "    const timeoutId = setTimeout(() => {\n"
            "      performSearch(query);\n"
            "    }, 500);\n"
            "\n"
            "    return () => clearTimeout(timeoutId);\n"
            "  }, [query]);\n"
            "\n"
            "  const performSearch = async (searchQuery: string) => {\n"
            "    setLoading(true);\n"
            "    setError(null);\n"
            "\n"
            "    try {\n"
            "      const response = await fetch(\n"
            "        `https://api.example.com/search?q=${encodeURIComponent(searchQuery)}`\n"
            "      );\n"
            "\n"
            "      if (!response.ok) {\n"
            "        throw new Error('Search failed');\n"
            "      }\n"
            "\n"
            "      const data = await response.json();\n"
            "      setResults(data.results);\n"
            "    } catch (err) {\n"
            "      setError('Failed to search. Please try again.');\n"
            "      setResults([]);\n"
            "    } finally {\n"
            "      setLoading(false);\n"
            "    }\n"
            "  };\n"
            "\n"
            "  const handleSelect = (result: SearchResult) => {\n"
            "    setQuery('');\n"
            "    setResults([]);\n"
            "    onResultSelect(result);\n"
            "  };\n"
            "\n"
            "  return (\n"
            "    <View style={styles.container}>\n"
            "      <TextInput\n"
            "        style={styles.input}\n"
            "        value={query}\n"
            "        onChangeText={setQuery}\n"
            "        placeholder={placeholder}\n"
            "        autoCapitalize=\"none\"\n"
            "        autoCorrect={false}\n"
            "      />\n"
            "\n"
            "      {loading && <ActivityIndicator style={styles.loader} />}\n"
            "\n"
            "      {error && <Text style={styles.error}>{error}</Text>}\n"
            "\n"
            "      {results.length > 0 && (\n"
            "        <FlatList\n"
            "          data={results}\n"
            "          keyExtractor={(item) => item.id}\n"
            "          renderItem={({ item }) => (\n"
            "            <TouchableOpacity\n"
            "              style={styles.resultItem}\n"
            "              onPress={() => handleSelect(item)}\n"
            "            >\n"
            "              <Text style={styles.resultTitle}>{item.title}</Text>\n"
            "              <Text style={styles.resultDescription}>\n"
            "                {item.description}\n"
            "              </Text>\n"
            "            </TouchableOpacity>\n"
            "          )}\n"
            "          style={styles.results}\n"
            "        />\n"
            "      )}\n"
            "    </View>\n"
            "  );\n"
            "};\n"
            "\n"
            "const styles = StyleSheet.create({\n"
            "  container: {\n"
            "    padding: 16,\n"
            "  },\n"
            "  input: {\n"
            "    height: 40,\n"
            "    borderColor: '#ccc',\n"
            "    borderWidth: 1,\n"
            "    borderRadius: 8,\n"
            "    paddingHorizontal: 12,\n"
            "    fontSize: 16,\n"
            "  },\n"
            "  loader: {\n"
            "    marginTop: 16,\n"
            "  },\n"
            "  error: {\n"
            "    color: 'red',\n"
            "    marginTop: 8,\n"
            "  },\n"
            "  results: {\n"
            "    marginTop: 8,\n"
            "  },\n"
            "  resultItem: {\n"
            "    padding: 12,\n"
            "    borderBottomWidth: 1,\n"
            "    borderBottomColor: '#eee',\n"
            "  },\n"
            "  resultTitle: {\n"
            "    fontSize: 16,\n"
            "    fontWeight: 'bold',\n"
            "  },\n"
            "  resultDescription: {\n"
            "    fontSize: 14,\n"
            "    color: '#666',\n"
            "    marginTop: 4,\n"
            "  },\n"
            "});\n"
            "\n"
            "export default SearchBar;"
        ),
    },
]

