"""PHP/Laravel Training Examples - 15 examples"""

LARAVEL_EXAMPLES = [
    {
        "instruction": "Generate Laravel Eloquent model with relationships and accessors.",
        "input": "Model: Order with user relationship, items, calculated total",
        "output": (
            "<?php\n"
            "\n"
            "namespace App\\Models;\n"
            "\n"
            "use Illuminate\\Database\\Eloquent\\Model;\n"
            "use Illuminate\\Database\\Eloquent\\Relations\\BelongsTo;\n"
            "use Illuminate\\Database\\Eloquent\\Relations\\HasMany;\n"
            "\n"
            "class Order extends Model\n"
            "{\n"
            "    protected $fillable = [\n"
            "        'user_id',\n"
            "        'status',\n"
            "        'shipping_address',\n"
            "        'payment_method',\n"
            "    ];\n"
            "\n"
            "    protected $casts = [\n"
            "        'shipping_address' => 'array',\n"
            "        'placed_at' => 'datetime',\n"
            "    ];\n"
            "\n"
            "    protected $appends = ['total', 'item_count'];\n"
            "\n"
            "    public function user(): BelongsTo\n"
            "    {\n"
            "        return $this->belongsTo(User::class);\n"
            "    }\n"
            "\n"
            "    public function items(): HasMany\n"
            "    {\n"
            "        return $this->hasMany(OrderItem::class);\n"
            "    }\n"
            "\n"
            "    public function getTotalAttribute(): float\n"
            "    {\n"
            "        return $this->items()->sum('subtotal');\n"
            "    }\n"
            "\n"
            "    public function getItemCountAttribute(): int\n"
            "    {\n"
            "        return $this->items()->sum('quantity');\n"
            "    }\n"
            "\n"
            "    public function scopePending($query)\n"
            "    {\n"
            "        return $query->where('status', 'pending');\n"
            "    }\n"
            "\n"
            "    public function scopeCompleted($query)\n"
            "    {\n"
            "        return $query->where('status', 'completed');\n"
            "    }\n"
            "}"
        ),
    },
    {
        "instruction": "Generate Laravel request validation class.",
        "input": "Request: Product creation with validation rules and custom messages",
        "output": (
            "<?php\n"
            "\n"
            "namespace App\\Http\\Requests;\n"
            "\n"
            "use Illuminate\\Foundation\\Http\\FormRequest;\n"
            "\n"
            "class StoreProductRequest extends FormRequest\n"
            "{\n"
            "    /**\n"
            "     * Determine if the user is authorized to make this request.\n"
            "     */\n"
            "    public function authorize(): bool\n"
            "    {\n"
            "        return $this->user()->can('create-products');\n"
            "    }\n"
            "\n"
            "    /**\n"
            "     * Get the validation rules that apply to the request.\n"
            "     */\n"
            "    public function rules(): array\n"
            "    {\n"
            "        return [\n"
            "            'name' => ['required', 'string', 'max:255'],\n"
            "            'description' => ['required', 'string'],\n"
            "            'price' => ['required', 'numeric', 'min:0'],\n"
            "            'category_id' => ['required', 'exists:categories,id'],\n"
            "            'stock' => ['required', 'integer', 'min:0'],\n"
            "            'images' => ['array', 'max:5'],\n"
            "            'images.*' => ['image', 'mimes:jpeg,png', 'max:2048'],\n"
            "            'tags' => ['array'],\n"
            "            'tags.*' => ['string', 'max:50'],\n"
            "        ];\n"
            "    }\n"
            "\n"
            "    /**\n"
            "     * Get custom messages for validator errors.\n"
            "     */\n"
            "    public function messages(): array\n"
            "    {\n"
            "        return [\n"
            "            'name.required' => 'Product name is required',\n"
            "            'price.min' => 'Price cannot be negative',\n"
            "            'category_id.exists' => 'Selected category does not exist',\n"
            "            'images.*.image' => 'Each file must be an image',\n"
            "            'images.*.max' => 'Images must not exceed 2MB',\n"
            "        ];\n"
            "    }\n"
            "\n"
            "    /**\n"
            "     * Get custom attributes for validator errors.\n"
            "     */\n"
            "    public function attributes(): array\n"
            "    {\n"
            "        return [\n"
            "            'category_id' => 'category',\n"
            "        ];\n"
            "    }\n"
            "}"
        ),
    },
    {
        "instruction": "Generate Laravel migration with indexes and foreign keys.",
        "input": "Migration: Create orders table with relationships and indexes",
        "output": (
            "<?php\n"
            "\n"
            "use Illuminate\\Database\\Migrations\\Migration;\n"
            "use Illuminate\\Database\\Schema\\Blueprint;\n"
            "use Illuminate\\Support\\Facades\\Schema;\n"
            "\n"
            "return new class extends Migration\n"
            "{\n"
            "    /**\n"
            "     * Run the migrations.\n"
            "     */\n"
            "    public function up(): void\n"
            "    {\n"
            "        Schema::create('orders', function (Blueprint $table) {\n"
            "            $table->id();\n"
            "            $table->foreignId('user_id')\n"
            "                  ->constrained()\n"
            "                  ->onDelete('cascade');\n"
            "            $table->string('order_number')->unique();\n"
            "            $table->enum('status', [\n"
            "                'pending',\n"
            "                'processing',\n"
            "                'shipped',\n"
            "                'delivered',\n"
            "                'cancelled'\n"
            "            ])->default('pending');\n"
            "            $table->decimal('subtotal', 10, 2);\n"
            "            $table->decimal('tax', 10, 2);\n"
            "            $table->decimal('shipping', 10, 2);\n"
            "            $table->decimal('total', 10, 2);\n"
            "            $table->json('shipping_address');\n"
            "            $table->string('payment_method');\n"
            "            $table->string('payment_status')->nullable();\n"
            "            $table->timestamp('placed_at')->nullable();\n"
            "            $table->timestamp('shipped_at')->nullable();\n"
            "            $table->timestamp('delivered_at')->nullable();\n"
            "            $table->timestamps();\n"
            "            $table->softDeletes();\n"
            "\n"
            "            // Indexes for better query performance\n"
            "            $table->index('user_id');\n"
            "            $table->index('status');\n"
            "            $table->index('order_number');\n"
            "            $table->index('placed_at');\n"
            "            $table->index(['user_id', 'status']);\n"
            "        });\n"
            "    }\n"
            "\n"
            "    /**\n"
            "     * Reverse the migrations.\n"
            "     */\n"
            "    public function down(): void\n"
            "    {\n"
            "        Schema::dropIfExists('orders');\n"
            "    }\n"
            "};"
        ),
    },
]

