"""Ruby/Rails Training Examples - 15 examples"""

RUBY_EXAMPLES = [
    {
        "instruction": "Generate Ruby model with validations and associations.",
        "input": "Model: Article with belongs_to user, has_many comments, validates presence of title",
        "output": (
            "# app/models/article.rb\n"
            "class Article < ApplicationRecord\n"
            "  belongs_to :user\n"
            "  has_many :comments, dependent: :destroy\n"
            "  has_many :tags, through: :article_tags\n"
            "\n"
            "  validates :title, presence: true, length: { minimum: 5, maximum: 200 }\n"
            "  validates :content, presence: true\n"
            "  validates :slug, presence: true, uniqueness: true, format: { with: /\\A[a-z0-9\\-]+\\z/ }\n"
            "\n"
            "  before_validation :generate_slug, on: :create\n"
            "  before_save :sanitize_content\n"
            "\n"
            "  scope :published, -> { where.not(published_at: nil) }\n"
            "  scope :recent, -> { order(created_at: :desc) }\n"
            "\n"
            "  def published?\n"
            "    published_at.present?\n"
            "  end\n"
            "\n"
            "  private\n"
            "\n"
            "  def generate_slug\n"
            "    self.slug = title.parameterize if title.present?\n"
            "  end\n"
            "\n"
            "  def sanitize_content\n"
            "    self.content = ActionController::Base.helpers.sanitize(content)\n"
            "  end\n"
            "end"
        ),
    },
    {
        "instruction": "Generate Rails API controller with proper error handling.",
        "input": "API Controller: Products with JSON responses, error handling, and status codes",
        "output": (
            "# app/controllers/api/v1/products_controller.rb\n"
            "module Api\n"
            "  module V1\n"
            "    class ProductsController < ApplicationController\n"
            "      before_action :set_product, only: [:show, :update, :destroy]\n"
            "      rescue_from ActiveRecord::RecordNotFound, with: :record_not_found\n"
            "      rescue_from ActiveRecord::RecordInvalid, with: :record_invalid\n"
            "\n"
            "      def index\n"
            "        @products = Product.all\n"
            "        @products = @products.where(category: params[:category]) if params[:category]\n"
            "        @products = @products.page(params[:page]).per(20)\n"
            "        \n"
            "        render json: {\n"
            "          data: @products,\n"
            "          meta: pagination_meta(@products)\n"
            "        }\n"
            "      end\n"
            "\n"
            "      def show\n"
            "        render json: @product\n"
            "      end\n"
            "\n"
            "      def create\n"
            "        @product = Product.new(product_params)\n"
            "        \n"
            "        if @product.save\n"
            "          render json: @product, status: :created\n"
            "        else\n"
            "          render json: { errors: @product.errors }, status: :unprocessable_entity\n"
            "        end\n"
            "      end\n"
            "\n"
            "      def update\n"
            "        if @product.update(product_params)\n"
            "          render json: @product\n"
            "        else\n"
            "          render json: { errors: @product.errors }, status: :unprocessable_entity\n"
            "        end\n"
            "      end\n"
            "\n"
            "      def destroy\n"
            "        @product.destroy\n"
            "        head :no_content\n"
            "      end\n"
            "\n"
            "      private\n"
            "\n"
            "      def set_product\n"
            "        @product = Product.find(params[:id])\n"
            "      end\n"
            "\n"
            "      def product_params\n"
            "        params.require(:product).permit(:name, :description, :price, :category, :stock)\n"
            "      end\n"
            "\n"
            "      def record_not_found\n"
            "        render json: { error: 'Product not found' }, status: :not_found\n"
            "      end\n"
            "\n"
            "      def record_invalid(e)\n"
            "        render json: { errors: e.record.errors }, status: :unprocessable_entity\n"
            "      end\n"
            "\n"
            "      def pagination_meta(collection)\n"
            "        {\n"
            "          current_page: collection.current_page,\n"
            "          total_pages: collection.total_pages,\n"
            "          total_count: collection.total_count\n"
            "        }\n"
            "      end\n"
            "    end\n"
            "  end\n"
            "end"
        ),
    },
    {
        "instruction": "Generate RSpec test for Rails model with associations.",
        "input": "Test: Article model with user relationship, validations, and scopes",
        "output": (
            "# spec/models/article_spec.rb\n"
            "require 'rails_helper'\n"
            "\n"
            "RSpec.describe Article, type: :model do\n"
            "  describe 'associations' do\n"
            "    it { should belong_to(:user) }\n"
            "    it { should have_many(:comments).dependent(:destroy) }\n"
            "    it { should have_many(:tags).through(:article_tags) }\n"
            "  end\n"
            "\n"
            "  describe 'validations' do\n"
            "    it { should validate_presence_of(:title) }\n"
            "    it { should validate_presence_of(:content) }\n"
            "    it { should validate_length_of(:title).is_at_least(5).is_at_most(200) }\n"
            "    it { should validate_uniqueness_of(:slug) }\n"
            "  end\n"
            "\n"
            "  describe 'scopes' do\n"
            "    let(:published_article) { create(:article, published_at: Time.current) }\n"
            "    let(:draft_article) { create(:article, published_at: nil) }\n"
            "\n"
            "    it 'returns only published articles' do\n"
            "      expect(Article.published).to include(published_article)\n"
            "      expect(Article.published).not_to include(draft_article)\n"
            "    end\n"
            "\n"
            "    it 'returns articles in descending order' do\n"
            "      old_article = create(:article, created_at: 1.day.ago)\n"
            "      new_article = create(:article, created_at: Time.current)\n"
            "      \n"
            "      expect(Article.recent.first).to eq(new_article)\n"
            "    end\n"
            "  end\n"
            "\n"
            "  describe '#published?' do\n"
            "    it 'returns true if published_at is present' do\n"
            "      article = build(:article, published_at: Time.current)\n"
            "      expect(article.published?).to be true\n"
            "    end\n"
            "\n"
            "    it 'returns false if published_at is nil' do\n"
            "      article = build(:article, published_at: nil)\n"
            "      expect(article.published?).to be false\n"
            "    end\n"
            "  end\n"
            "\n"
            "  describe 'callbacks' do\n"
            "    it 'generates slug from title before validation' do\n"
            "      article = build(:article, title: 'My Great Article', slug: nil)\n"
            "      article.valid?\n"
            "      expect(article.slug).to eq('my-great-article')\n"
            "    end\n"
            "\n"
            "    it 'sanitizes content before save' do\n"
            "      article = create(:article, content: '<script>alert(1)</script><p>Safe</p>')\n"
            "      expect(article.content).not_to include('<script>')\n"
            "      expect(article.content).to include('<p>Safe</p>')\n"
            "    end\n"
            "  end\n"
            "end"
        ),
    },
]

